#!/bin/env bash
if [ -z "$1" ]
 then echo " ! no image selected."
 exit 1
fi

orig_img=$1
spa="\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
isize=$(identify $orig_img | awk '{print $3}' | cut -d "x" -f2)

if [ "$isize" -gt "750" ]
 then cnv="yes"
 else cnv=""
fi &&

clear && echo -e "$spa$spa$spa$spa" &&

if [ -z "$cnv" ]
 then
  echo -e "2;3;\n0;1;0;0;0;0;0;0;0;0;${orig_img}\n4;\n3;" | /usr/lib/w3m/w3mimgdisplay
 else
  convert $orig_img -resize x750 /tmp/dimg.tmp &&
  echo -e "2;3;\n0;1;0;0;0;0;0;0;0;0;/tmp/dimg.tmp\n4;\n3;" | /usr/lib/w3m/w3mimgdisplay &&
  rm -rf /tmp/dimg.tmp
fi
