#!/bin/sh
# dnscrypt-proxy init script for sysvinit + start-stop-daemon
# apathy 1.2 - mssx86 (mssftw@protonmail.com)

set -e
. /lib/lsb/init-functions

NAME=dnscrypt-proxy
PIDFILE=/run/$NAME.pid
DAEMON=/opt/dnscrypt-proxy/dnscrypt-proxy
DAEMON_OPTS=""
USER=root

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
 start)
  log_info_msg "apathy - starting $NAME."
  start-stop-daemon --start --quiet -b -m --pidfile $PIDFILE --chuid $USER --exec $DAEMON
  evaluate_retval
  ;;
 stop)
  log_info_msg "apathy - stopping $NAME."
  start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
  evaluate_retval
  ;;
 restart)
  ${0} stop
  sleep 1
  ${0} start
  ;;
 status)
  statusproc $DAEMON
  ;;
 *)
  echo "Usage: "$1" {start|stop|restart}"
  exit 1
esac
