#!/bin/sh
# default-start: 3 4 5
# default-stop:	 0 1 2 6	

. /lib/lsb/init-functions

case "${1}" in
   start)
      log_info_msg "starting mpd"
      start_daemon /usr/bin/mpd /etc/mpd.conf
      ;;

   stop)
      log_info_msg "stopping mpd"
      killproc /usr/bin/mpd
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   *)
      echo "Usage: ${0} {start|stop|restart}"
      exit 1
      ;;
esac

exit 0
