#!/bin/sh
# dnscrypt-proxy init script for sysvinit + start-stop-daemon
# apathy 1.2 - mssx86 (mssftw@protonmail.com)

set -e
. /lib/lsb/init-functions

NAME=transmission-daemon
DAEMON=/usr/bin/transmission-daemon
DAEMON_OPTS="-g /home/mss/.config/transmission-daemon"
USER=mss

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
 start)
  log_info_msg "apathy - starting $NAME."
  start-stop-daemon --start --quiet  --chuid $USER --exec $DAEMON -- $DAEMON_OPTS
  evaluate_retval
  ;;
 stop)
  log_info_msg "apathy - stopping $NAME."
  kill $(pidof transmission-daemon)
  evaluate_retval
  ;;
 restart)
  ${0} stop
  sleep 1
  ${0} start
  ;;
 status)
  transmission-remote -n mss:mss -l
  ;;
 *)
  echo "Usage: "$1" {start|stop|restart}"
  exit 1
esac
