#!/bin/sh
# alsa init script for sysvinit
# apathy 1.2 - mssx86 (mss@waifu.club)

# default-start --> S
# default-stop ---> 0 1 6
# description ----> (re)stores alsamixer settings from/to /var/lib/alsa/asound.state.

. /lib/lsb/init-functions

case "$1" in
 start)
  log_info_msg "restoring ${c_lcyan}alsa${c_reset} volumes."
  /usr/sbin/alsactl restore
  evalret
 ;;

 stop)
  log_info_msg "saving ${c_lcyan}alsa${c_reset} volumes."
  /usr/sbin/alsactl store
  evalret
 ;;

 *)
  printf "usage: $0 {start|stop}.\n"
  exit 1
 ;;
esac
