#!/bin/sh
# cleanfs init script for sysvinit
# apathy 1.2 - mssx86 (mss@waifu.club)

# default-start --> S
# default-stop ---> 0 1 6
# description ----> cleans /var/{run,lock} and /tmp, creates /var/run/utmp
#                   and dirs defined in /etc/sysconfig/createfiles

. /lib/lsb/init-functions

create_files(){
 # input to file descriptor 9 and output to stdin (redirection)
 exec 9>&0 < /etc/sysconfig/createfiles

 while read name type perm usr grp dtype maj min junk
 do
  # ignore comments and blank lines.
  case "${name}" in ""|\#*) continue ;; esac

  # ignore existing files.
  if [ ! -e "${name}" ]
   then
    # create stuff based on its type.
    case "${type}" in
     dir)	mkdir "${name}" ;;
     file)	:> "${name}"	;;
     dev)
      case "${dtype}" in
       char)	mknod "${name}" c ${maj} ${min}				;;
       block)	mknod "${name}" b ${maj} ${min}				;;
       pipe)	mknod "${name}" p					;;
       *)	log_warning_msg "unknown device type: ${dtype}"	;;
      esac
     ;;
     *)		log_warning_msg "unknown type: ${type}"; continue	;;
    esac

    # set up the permissions, too.
    chown ${usr}:${grp} "${name}"
    chmod ${perm} "${name}"
   fi
 done

 # close file descriptor 9 (end redirection)
 exec 0>&9 9>&-
 return 0
}

case "${1}" in
 start)
  log_info_msg "cleaning file systems: "

  if [ "${SKIPTMPCLEAN}" = "" ]; then
   log_info_msg2 "${c_lcyan}/tmp"
   cd /tmp &&
   find . -xdev -mindepth 1 ! -name lost+found -delete || failed=1
  fi
  
  printf "${c_reset}"

  > /var/run/utmp

  if grep -q '^utmp:' /etc/group; then
   chmod 664 /var/run/utmp
   chgrp utmp /var/run/utmp
  fi

  (exit ${failed})
  evalret

  if egrep -qv '^(#|$)' /etc/sysconfig/createfiles 2>/dev/null; then
   log_info_msg "creating files and directories. "
   create_files      # always returns 0
   evalret
  fi

  exit $failed
 ;;
 *)
  printf "usage: ${0} {start}.\n"
  exit 1
 ;;
esac
