#!/mss/bin/sh
# console init script for sysvinit
# apathy 1.3 - mssx86 (mss@waifu.club)

# default-start --> S
# description ----> set up fonts and lang settings from /etc/sysconfig/console

. /mss/bin/apathy-funcs-init

# set console variables
UNICODE="1"
KEYMAP="us"
FONT="ter12n -m 8859-1"

case "${1}" in
 start)

  log_info_msg "setting up the ${c_lcyan}linux console${c_reset}."
  
  # a >> if fb console is used, set font in utf8 for every console
  if [ -d /sys/class/graphics/fb0 ]; then setfont ${FONT}; fi

  # b >> figure out the command to set the console into the desired mode
  MODE_COMMAND="printf '\033%G' && kbd_mode -u" \
   || MODE_COMMAND="printf '\033%@\033(K' && kbd_mode -a" \
   || failed=1

  # c >> apply the mode setting command to all terms in inittab
  for TTY in $(grep 'respawn' /etc/inittab | awk '{gsub("--noclear",""); gsub("tty",""); print $2}')
   do
    openvt -f -w -c ${TTY} -- /bin/sh -c '${MODE_COMMAND}' || failed=1
   done

  # d >> set keymap
  loadkeys ${KEYMAP} >/dev/null 2>&1 || failed=1

  # e >> if anything failed, exit with it
  (exit $failed); evalret; exit $failed
 ;;
 *)
  printf "usage: ${0} {start}.\n"
  exit 1
 ;;
esac
