#!/bin/sh
# gpm init script for sysvinit
# apathy 1.2 - mssx86 (mss@waifu.club)

# default-start --> 3 4 5
# default-stop ---> 0 1 2 6
# description ----> starts and stops gpm.

. /lib/lsb/init-functions

pidfile="/run/gpm.pid"

# set mouse variables
MDEVICE="/dev/input/mice"
PROTOCOL="imps2"
GPMOPTS=""

case "${1}" in
 start)
  log_info_msg "apathy - starting gpm."  
  start_daemon /usr/sbin/gpm -m "${MDEVICE}" -t "${PROTOCOL}" ${GPMOPTS}
  evaluate_retval
 ;;
 
 stop)
  log_info_msg "apathy - stopping gpm."
  killproc /usr/sbin/gpm
  evaluate_retval
 ;;

 restart)
  ${0} stop
   sleep 1
  ${0} start
 ;;

 status)
  statusproc /usr/sbin/gpm
 ;;

 *)
  printf "usage: ${0} {start|stop|restart|status}.\n"
  exit 1
 ;;
esac

exit 0
