#!/bin/sh
# alsa init script for sysvinit
# apathy 1.2 - mssx86 (mss@waifu.club)

# default-start --> 3 4 5
# default-stop ---> 
# description ----> sets iptables up.

. /lib/lsb/init-functions

case "$1" in
 start)
  if [ -x /etc/rc.d/rc.iptables ]; then
   log_info_msg "apathy - starting ${c_lcyan}iptables${c_reset}."
   /etc/rc.d/rc.iptables
   evalret
  fi
 ;;

 lock)
  log_info_msg "apathy - locking system iptables firewall."
  /sbin/iptables	--policy INPUT		DROP
  /sbin/iptables	--policy OUTPUT		DROP
  /sbin/iptables	--policy FORWARD	DROP
  /sbin/iptables	--flush
  /sbin/iptables	-t mangle --flush
  /sbin/iptables	--delete-chain
  /sbin/iptables	-t mangle --delete-chain
  /sbin/iptables	-A INPUT  -i lo -j ACCEPT
  /sbin/iptables	-A OUTPUT -o lo -j ACCEPT
  evalret
 ;;

 clear)
  log_info_msg "apathy - clearing system iptables iptables."
  /sbin/iptables	--policy INPUT		ACCEPT
  /sbin/iptables	--policy OUTPUT		ACCEPT
  /sbin/iptables	--policy FORWARD	ACCEPT
  /sbin/iptables	--flush
  /sbin/iptables	-t mangle --flush
  /sbin/iptables	--delete-chain
  /sbin/iptables	-t mangle --delete-chain
  evalret
 ;;

 status)
  /sbin/iptables	--numeric --list
  /sbin/iptables	-t mangle --numeric --list
 ;;

 *)
  printf "usage: $0 {start|clear|lock|status}.\n"
  exit 1
 ;;
esac
