#!/bin/sh
# localnet init script for sysvinit
# apathy 1.2 - mssx86 (mss@waifu.club)

# default-start --> S
# default-stop ---> 0 6
# description ----> sets the hostname and starts the loopback interface.

. /lib/lsb/init-functions

# source if /etc/sysconfig/network exists
[ -f /etc/sysconfig/network ] && . /etc/sysconfig/network

# set hostname form /etc/hostname
[ -f /etc/hostname ] && hname=$(cat /etc/hostname)

case "${1}" in
 start)
  log_info_msg "bringing up the loopback interface."
  ip addr add 127.0.0.1/8 label lo dev lo
  ip link set lo up
  evalret

  log_info_msg "setting the hostname to ${c_lcyan}${hname}${c_reset}."
  hostname ${hname}
  evalret
 ;;

 stop)
  log_info_msg "bringing down the loopback interface."
  ip link set lo down
  evalret
 ;;

 restart)
  ${0} stop
   sleep 1
  ${0} start
 ;;

 status)
  log_info_msg "hostname is set to: ${c_lcyan}$(hostname)${c_reset}."
  ip link show lo
 ;;

 *)
  printf "usage: ${0} {start|stop|restart|status}.\n"
  exit 1
 ;;
esac

exit 0
