#!/bin/sh
# mpd init script for sysvinit + start-stop-daemon
# apathy 1.2 - mssx86 (mssftw@protonmail.com)

set -e
. /lib/lsb/init-functions

NAME=mpd
PIDFILE=/run/$NAME.pid
DAEMON=/usr/bin/mpd
DAEMON_OPTS="-p $PIDFILE /etc/mpd.conf"
USER=mpd

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
 start)
  log_info_msg "apathy - starting ${c_lcyan}$NAME${c_reset}."
  start-stop-daemon --start --quiet -b --chuid $USER --exec $DAEMON $DAEMON_OPTS
  evalret
  ;;
 stop)
  log_info_msg "apathy - stopping ${c_lcyan}$NAME${c_reset}."
  start-stop-daemon --stop --quiet --oknodo --pidfile "$PIDFILE" 
  evalret
  ;;
 restart)
  ${0} stop
  sleep 1
  ${0} start
  ;;
 status)
  statusproc $DAEMON
  ;;
 *)
  echo "Usage: "$1" {start|stop|restart}"
  exit 1
esac
