#!/mss/bin/sh
# random init script for sysvinit
# apathy 1.2 - mssx86 (mss@waifu.club)

# default-start --> 2 3 4 5
# default-stop ---> 0 1 6
# description ----> initalises /dev/urandom

. /lib/lsb/init-functions

case "${1}" in
 start)
  log_info_msg "initalizing the ${c_lcyan}kernel random number generator${c_reset}."

  if [ -f /var/tmp/random-seed ]
   then /bin/cat /var/tmp/random-seed > /dev/urandom
  fi

  /bin/dd if=/dev/urandom of=/var/tmp/random-seed count=1 > /dev/null 2>&1
  evalret
 ;;

 stop)
  log_info_msg "saving ${c_lcyan}random seed${c_reset} to ${c_lcyan}/var/tmp${c_reset}."

  /bin/dd if=/dev/urandom of=/var/tmp/random-seed count=1 > /dev/null 2>&1
  evalret
 ;;
 
 *)
  printf "usage: ${0} {start|stop}.\n"
  exit 1
 ;;
esac
