#!/bin/sh
# setclock init script for sysvinit
# apathy 1.2 - mssx86 (mss@waifu.club)

# default-start --> S
# description ----> saves and restores the hwclock.

. /lib/lsb/init-functions

case ${1} in
 start)
  hwclock --hctosys --utc > /dev/null
 ;;

 stop)
  log_info_msg "apathy - setting the hardware clock."
  hwclock --systohc > /dev/null
  evalret
 ;;

 *)
  printf "usage: ${0} {start|stop}.\n"
  exit 1
 ;;
esac

exit 0
