#!/mss/bin/sh
# sysctl init script for sysvinit
# apathy 1.2 - mssx86 (mss@waifu.club)

# default-start --> S
# description ----> manipulates the procfs based on /etc/sysctl.conf

. /mss/bin/apathy-funcs-init

case "${1}" in
 start)
  if [ -f "/etc/sysctl.conf" ]; then
   log_info_msg "setting kernel runtime parameters."
   sysctl -q -p
   evalret
  fi
 ;;

 status)
  sysctl -a
 ;;

 *)
  printf "usage: ${0} {start|status}.\n"
  exit 1
 ;;
esac

exit 0
