#!/bin/sh
# sysklogd init script for sysvinit
# apathy 1.2 - mssx86 (mss@waifu.club)

# default-start --> 3 4 5
# default-stop ---> 0 1 2 6
# description ----> starts kernel and system log daemons.

. /lib/lsb/init-functions

case "${1}" in
 start)
  log_info_msg "starting the ${c_lcyan}system log${c_reset} daemon."
   parms=${SYSKLOGD_PARMS-'-m 0'}
   start_daemon /sbin/syslogd $parms
  evalret

  log_info_msg "starting the ${c_lcyan}kernel log${c_reset} daemon."
   start_daemon /sbin/klogd
  evalret
 ;;

 stop)
  log_info_msg "stopping the ${c_lcyan}kernel log${c_reset} daemon."
   killproc /sbin/klogd
  evalret

  log_info_msg "stopping the ${c_lcyan}system log${c_reset} daemon."
   killproc /sbin/syslogd
  evalret
 ;;

 restart)
  ${0} stop
   sleep 1
  ${0} start
 ;;

 status)
  statusproc /sbin/syslogd
  statusproc klogd
 ;;

 *)
  printf "Usage: ${0} {start|stop|restart|status}.\n"
  exit 1
 ;;
esac
