#!/bin/sh
# udev_retry init script for sysvinit
# apathy 1.2 - mssx86 (mss@waifu.club)

# default-start --> S
# description ----> retries failed uevents.

. /lib/lsb/init-functions

case "${1}" in
 start)
  log_info_msg "apathy - retrying failed ${c_lcyan}uevents${c_reset} if there are any."
  rundir=/run/udev
  
  #copy the rules generated before / was mounted read-write:
  for file in ${rundir}/tmp-rules--*
   do
    dest=${file##*tmp-rules--}
    [ "$dest" = '*' ] && break
    cat $file >> /etc/udev/rules.d/$dest
    rm -f $file
   done

  # re-trigger the uevents that may have failed,
  /bin/sed -e 's/#.*$//' /etc/sysconfig/udev_retry | /bin/grep -v '^$' | \
  while read line
   do
    for subsystem in $line
     do
      /sbin/udevadm trigger --subsystem-match=$subsystem --action=add
     done
   done

  # now wait for udevd to process the uevents we triggered
  if ! is_true "$OMIT_UDEV_RETRY_SETTLE"; then
   /sbin/udevadm settle
  fi

  evalret
 ;;

 *)
  printf "usage: ${0} {start}.\n"
  exit 1
 ;;
esac

exit 0
