// act as firefox 52-esr by default
pref("general.useragent.override",             "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0");

// site specific overrides
pref("general.useragent.override.pixiv.net",   "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0");
pref("general.useragent.override.deezer.com",  "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0");
pref("general.useragent.override.twitter.com", "FUCK"
