#!/mss/bin/sh
### cfg
scriptdir="/home/mss/.config/scripts"
blockdir="/home/mss/.config/lemonbar/blocklets"
tmpdir="/tmp/lemonbar"

fr='%{F-}' f1='%{F#ababab}' f2='%{F#747474}' f3='%{F#e62063}' f4='%{F#464646}' f5='%{F#6d7373}'
br='%{B-}' b1='%{B#101010}' b2='%{B#464646}' b3='%{B#e62063}' b4="%{B#}"

sep=" ${b1} ${br} "

### blocklets
if [ ! -d "/tmp/lemonbar" ]; then mkdir "/tmp/lemonbar"; fi

. /home/mss/.config/lemonbar/blocklets

  _pgid          & #pgid
  _uptime        & #uptime
  bw             & #bw
  cap_alsa       & #cap_alsa
  cpustat        & #cpustat
  mas_alsa       & #mas_alsa
  mem            & #mem
  mpdstat        & #mpdstat
  mpdvol         & #mpdvol
  weat           & #weat
# wspace         & #wspace
  wspace_simple  & #wspace_simple

while true; do
 time=$(date '+%a %d %I:%M:%S%P')
 read _pgid       < "${tmpdir}"/pgid
 read _uptime     < "${tmpdir}"/uptime
 read bw          < "${tmpdir}"/bw
 read cap_alsa    < "${tmpdir}"/cap_alsa
 read cpustat     < "${tmpdir}"/cpustat
 read mas_alsa    < "${tmpdir}"/mas_alsa
 read mem         < "${tmpdir}"/mem
 read mpdstat     < "${tmpdir}"/mpdstat
 read mpdvol      < "${tmpdir}"/mpdvol
 read weat        < "${tmpdir}"/weat
 read wspace      < "${tmpdir}"/wspace

echo "\
%{l}\
${wspace}${sep}\
${f2}pgid ${f3}[${fr}${_pgid}${f3}]${fr}${sep}\
${f1}${cpustat} ${f1}${mem}${fr}${sep}\
${f2}${bw}${fr}\
%{c}\
${f1}${time}${fr} ${f2}${weat}${fr}\
%{r}${f1}${mpdstat}${fr}${sep}\
${f1}${mas_alsa}${fr} ${f2}${mpdvol}${fr} ${f1}${cap_alsa}${fr}${sep}\
${f5}${_uptime}${fr} "

 sleep 0.3
done
