#!/mss/bin/sh

case $1 in
 full|-f)   kek="full"   c_bg="000000" c_fg="ffffff" ;;
 simple|-s) kek="simple" c_bg="000000" c_fg="ffffff" ;;
 *)         exit 1                                   ;;
esac

if [ -z "$(pidof lemonbar)" ]
 then
  ps -o pgid -p "$$" | tail -1 | sed 's/ //g' > /tmp/lemonbar.pid

  /home/mss/.config/lemonbar/"${kek}"              \
   | lemonbar -p -b -d -a 20                       \
   -g "1366x12+0+0"                                \
   -f "scientifica-7:antialias=true:autohint=true" \
   -f "euphon-10"                                  \
   -B "#${c_bg}" -F "#${c_fg}" -U "#FF00FF"        \
   | sh
 else
  kill -KILL -$(cat /tmp/lemonbar.pid)
fi
