#!/mss/bin/sh
### cfg
scriptdir="/home/mss/.config/scripts"
blockdir="/home/mss/.config/lemonbar/blocklets"
tmpdir="/tmp/lemonbar"

cr='%{F-}'
c1='%{F#ababab}'
c2='%{F#e3e3e3}'
c3='%{F#747474}'
c4='%{F#f7f7f7}'
c5='%{F#999999}'
c6='%{F#e62063}'
c7='%{F#464646}'
c8='%{F#6d7373}'

sep_color="${c7}"
sep="${c7} | ${cr}"

### blocklets
if [ ! -d "/tmp/lemonbar" ]; then mkdir "/tmp/lemonbar"; fi

. /home/mss/.config/lemonbar/blocklets

_pgid          & #pgid
_uptime        & #uptime
bw             & #bw
cap_alsa       & #cap_alsa
cpustat        & #cpustat
mas_alsa       & #mas_alsa
mem            & #mem
mpdstat        & #mpdstat
mpdvol         & #mpdvol
weat           & #weat
wspace         & #wspace

while true; do
 time=$(date '+%a %d %I:%M:%S%P')
 read _pgid       < "${tmpdir}"/pgid
 read _uptime     < "${tmpdir}"/uptime
 read bw          < "${tmpdir}"/bw
 read cap_alsa    < "${tmpdir}"/cap_alsa
 read cpustat     < "${tmpdir}"/cpustat
 read mas_alsa    < "${tmpdir}"/mas_alsa
 read mem         < "${tmpdir}"/mem
 read mpdstat     < "${tmpdir}"/mpdstat
 read mpdvol      < "${tmpdir}"/mpdvol
 read weat        < "${tmpdir}"/weat
 read wspace      < "${tmpdir}"/wspace

echo "%{l}\
${wspace}${sep}\
pgid: ${c6}${_pgid}${cr}${sep}\
${c2}${cpustat}${cr} ${c2}${mem}${cr}${sep}\
${c1}${bw}${cr}\
%{c}${c2}${time}${cr} ${c3}${weat}${cr}\
%{r}${c1}${mpdstat}${cr}${sep}\
${c4}${mas_alsa}${cr} ${c5}${mpdvol}${cr} ${c4}${cap_alsa}${cr}${sep}\
${c8}${_uptime}${cr} "

 sleep 0.2
done
