#!/mss/bin/sh
### cfg
scriptdir="/home/mss/.config/scripts"
blockdir="/home/mss/.config/lemonbar/blocklets"
tmpdir="/tmp/lemonbar"

cr='%{F-}'
c1='%{F#ababab}'
c2='%{F#e3e3e3}'
c3='%{F#747474}'
c4='%{F#f7f7f7}'
c5='%{F#999999}'
c6='%{F#e62063}'
c7='%{F#464646}'
c8='%{F#6d7373}'

sep_color="${c7}"
sep="${c7} | ${cr}"

### blocklets
if [ ! -d "/tmp/lemonbar" ]; then mkdir "/tmp/lemonbar"; fi

. /home/mss/.config/lemonbar/blocklets
_pid
_uptime      &
_weather     &
mpdstat      &
mpdvol       &
workspace    &
capture_alsa &
master_alsa  &

while true; do
 time=$(date '+%a %d %I:%M:%S%P')
 read uptime       < "${tmpdir}"/uptime
 read weather      < "${tmpdir}"/weather
 read master_alsa  < "${tmpdir}"/master-alsa
 read mpdstat      < "${tmpdir}"/mpdstat
 read mpdvol       < "${tmpdir}"/mpdvol
 read capture_alsa < "${tmpdir}"/capture-alsa
 read _uptime      < "${tmpdir}"/uptime
 read wspace       < "${tmpdir}"/wspace
 read _pid         < "${tmpdir}"/pid

echo "%{l} ${c8}${_uptime}${cr}${sep}\
pgid: ${c6}${_pid}${cr}${sep}\
wspace: ${c3}${wspace}${cr}\
%{c}${c2}${time}${cr} ${c3}${weather}${cr}\
%{r}${c1}${mpdstat}${cr}${sep}\
${c4}${master_alsa}${cr} ${c5}${mpdvol}${cr} ${c4}${capture_alsa}${cr} "

 sleep 0.2
done
