#!/mss/bin/sh
fr='%{F-}' f1='%{F#000000}' f2='%{F#FFFFFF}' f3='%{F#ababab}' f4='%{F#7c7c7c}'
br='%{B-}' b1='%{B#101010}' b2='%{B#464646}' 
 
read _pgid < /tmp/lemonbar.pid

while true; do
 read load < /proc/loadavg  
 read rx < "/sys/class/net/eth0/statistics/rx_bytes"
 read tx < "/sys/class/net/eth0/statistics/tx_bytes"
 time="$(date '+%a %d %I:%M:%S%P')"

 _rx="$(($rx / 1048576))"
 _tx="$(($tx / 1048576))"

 mpd="$(mpc current | awk -v len=40 '{ if (length($0) > len) print substr($0, 1, len-3) "..."; else print; }')"
 [ -z "${mpd}" ] && mpd="mpd is idle."

 curr_ws="$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')"
 curr_before="$((${curr_ws} - 1))"
 curr_after="$((${curr_ws} + 1))"
 [ "${curr_before}" -eq 0 ] && curr_before="4"
 [ "${curr_after}"  -eq 5 ] && curr_after="1"

 echo "\
%{l}\
%{A5:wmctrl -s ${curr_before}:}\
%{A4:wmctrl -s ${curr_after}:}\
 ${f3}${b1} workspace${fr} ${f4}[${f2}${curr_ws}${f4}] ${fr}${br}\
%{A5}%{A4}\
 ${b2}${f3} pgid ${f1}${_pgid} ${fr}${br}\
 ${b1}${f3} rx ${f2}${_rx} ${f3}tx ${f2}${_tx} ${fr}${br}\
%{r}\
${f2}${b1} ${load} ${fr}${br} \
%{A:mpc next:}\
%{A2:mpc toggle:}\
%{A3:mpc prev:}\
%{A4:mpc volume +10:}\
%{A5:mpc volume -10:}\
${f3}${b1} ${mpd} ${fr}${br} \
%{A5}%{A4}%{A3}%{A2}%{A}\
%{A3:amixer -q -D default sset Master toggle     :}\
%{A4:amixer -q -D default sset Master 3dB+ unmute:}\
%{A5:amixer -q -D default sset Master 3dB- unmute:}\
${f1}${b2} mas${fr}%{A}%{A}%{A}\
%{A3:amixer -q -D default sset Capture toggle     :}\
%{A4:amixer -q -D default sset Capture 3dB+ unmute:}\
%{A5:amixer -q -D default sset Capture 3dB- unmute:}\
${f1} cap ${fr}${br}%{A}%{A}%{A} \
${f2}${b1} ${time} ${fr}${br} "

 sleep 0.2
done
