#define CUM (){ return 0;}

int gdk_wayland_device_get_wl_pointer            CUM             
int gdk_wayland_display_get_wl_compositor        CUM             
int gdk_wayland_display_get_wl_display           CUM             
int gdk_wayland_window_get_wl_surface            CUM             
int wl_buffer_interface                          CUM             
int wl_callback_interface                        CUM             
int wl_compositor_interface                      CUM             
int wl_data_device_interface                     CUM             
int wl_data_device_manager_interface             CUM             
int wl_display_cancel_read                       CUM             
int wl_display_connect                           CUM             
int wl_display_connect_to_fd                     CUM             
int wl_display_create_queue                      CUM             
int wl_display_disconnect                        CUM             
int wl_display_dispatch                          CUM             
int wl_display_dispatch_pending                  CUM             
int wl_display_dispatch_queue                    CUM             
int wl_display_dispatch_queue_pending            CUM             
int wl_display_flush                             CUM             
int wl_display_get_error                         CUM             
int wl_display_get_fd                            CUM             
int wl_display_get_protocol_error                CUM             
int wl_display_prepare_read                      CUM             
int wl_display_prepare_read_queue                CUM             
int wl_display_read_events                       CUM             
int wl_display_roundtrip                         CUM             
int wl_display_roundtrip_queue                   CUM             
int wl_egl_window_create                         CUM             
int wl_egl_window_destroy                        CUM             
int wl_egl_window_resize                         CUM             
int wl_event_queue_destroy                       CUM             
int wl_keyboard_interface                        CUM             
int wl_list_empty                                CUM             
int wl_list_init                                 CUM             
int wl_list_insert                               CUM             
int wl_list_insert_list                          CUM             
int wl_list_length                               CUM             
int wl_list_remove                               CUM             
int wl_log_set_handler_client                    CUM             
int wl_output_interface                          CUM             
int wl_pointer_interface                         CUM             
int wl_proxy_add_dispatcher                      CUM             
int wl_proxy_add_listener                        CUM             
int wl_proxy_create                              CUM             
int wl_proxy_create_wrapper                      CUM             
int wl_proxy_destroy                             CUM             
int wl_proxy_get_class                           CUM             
int wl_proxy_get_id                              CUM             
int wl_proxy_get_listener                        CUM             
int wl_proxy_get_user_data                       CUM             
int wl_proxy_get_version                         CUM             
int wl_proxy_marshal                             CUM             
int wl_proxy_marshal_array                       CUM             
int wl_proxy_marshal_array_constructor           CUM             
int wl_proxy_marshal_array_constructor_versioned CUM             
int wl_proxy_marshal_constructor                 CUM             
int wl_proxy_marshal_constructor_versioned       CUM             
int wl_proxy_marshal_flags                       CUM             
int wl_proxy_set_queue                           CUM             
int wl_proxy_set_user_data                       CUM             
int wl_proxy_wrapper_destroy                     CUM             
int wl_region_interface                          CUM             
int wl_registry_interface                        CUM             
int wl_seat_interface                            CUM             
int wl_shm_interface                             CUM             
int wl_shm_pool_interface                        CUM             
int wl_subcompositor_interface                   CUM             
int wl_subsurface_interface                      CUM             
int wl_surface_interface                         CUM             
