pref("accessibility.force_disabled", 1);
pref("browser.aboutConfig.showWarning", false);
pref("browser.cache.disk.enable", false);
pref("browser.cache.memory.enable", true);
pref("browser.cache.offline.enable", false);
pref("browser.cache.offline.storage.enable", false);
pref("browser.compactmode.show", true);
pref("browser.contentblocking.category", "standard");
pref("browser.download.autohideButton", false);
pref("browser.download.hide_plugins_without_extensions", false);
pref("browser.download.manager.addToRecentDocs", false);
pref("browser.download.useDownloadDir", false);
pref("browser.newtabpage.enabled", false);
pref("browser.preferences.defaultPerformanceSettings.enabled", false);
pref("browser.proton.toolbar.version", 3);
pref("browser.safebrowsing.downloads.enabled", false);
pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
pref("browser.safebrowsing.malware.enabled", false);
pref("browser.safebrowsing.phishing.enabled", false);
pref("browser.sessionstore.resume_from_crash", true);
pref("browser.shell.checkDefaultBrowser", false);
pref("browser.startup.homepage", "about:newtab");
pref("browser.startup.page", 0);
pref("browser.toolbars.bookmarks.visibility", "always");
pref("browser.uidensity", 1);
pref("dom.allow_cut_copy", true);
pref("dom.event.clipboardevents.enabled", true);
pref("dom.ipc.processCount", 2);
pref("dom.w3c_touch_events.enabled", 1);
pref("findbar.highlightAll", true);
pref("font.default.x-western", "sans-serif");
pref("font.name.monospace.ja", "xos4 Terminus");
pref("font.name.monospace.x-western", "xos4 Terminus");
pref("font.name.sans-serif.ja", "xos4 Terminus");
pref("font.name.sans-serif.x-western", "Liberation Sans");
pref("font.name.serif.ja", "xos4 Terminus");
pref("font.name.serif.x-western", "Liberation Sans");
pref("general.autoScroll", false);
pref("general.smoothScroll", false);
pref("general.warnOnAboutConfig", false);
pref("media.hardwaremediakeys.enabled", false);
pref("media.videocontrols.picture-in-picture.video-toggle.enabled", false);
pref("middlemouse.contentLoadURL", false);
pref("network.security.esni.enabled", false);
pref("network.trr.mode", 0);
pref("reader.color_scheme", "dark");
pref("startup.homepage_override_url", "about:newtab");
pref("startup.homepage_welcome_url", "about:newtab");
pref("toolkit.cosmeticAnimations.enabled", false);
pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
pref("ui.systemUsesDarkTheme", true);
