#!/mss/bin/sh
. /mss/init/files/funcs
. /mss/files/init.conf

# 1 > silence dmesg
dmesg --console-off

# 2 > funcs
initboi(){
 ctrlaltdel -s; banner

 ainitmes "mounting ${cb_cyn}pseudo${c_res} filesystems."
  ainit_mount nosuid,noexec,nodev    proc     proc /proc &&
  ainit_mount nosuid,noexec,nodev    sysfs    sys  /sys  &&
  ainit_mount defaults               tmpfs    run  /run  &&
  ainit_mount mode=0755,nosuid       devtmpfs dev  /dev  &&

  mkdir -p   /run/lock /run/shm /dev/pts &&
  chmod 1777 /run/lock /run/shm          &&
  ln    -sfn /run/shm  /dev/shm          &&

  ainit_mount gid=5,mode=620 devpts devpts /dev/pts
 evalret

 ainitmes "starting ${cb_cyn}udev${c_res}."
  udevd   -d                           &&
  udevadm trigger -c add -t subsystems &&
  udevadm trigger -c add -t devices    &&
  udevadm settle
 evalret

 ainitmes "remounting ${cb_cyn}rootfs${c_res} (ro)."
  mount -o remount,ro /     >/dev/null 2>&1
 evalret

 ainitmes "running ${cb_cyn}fsck${c_res}."
  fsck -ATat noopts=_netdev >/dev/null 2>&1
 evalret

 ainitmes "remounting ${cb_cyn}rootfs${c_res} (rw)."
  mount -o remount,rw /     >/dev/null 2>&1
 evalret

 ainitmes "mounting the entries in ${cb_cyn}fstab${c_res}."
  mount -a                  >/dev/null 2>&1
 evalret

 ainitmes "seeding ${cb_cyn}random${c_res}."
  [ -f /var/tmp/random-seed ] && cat /var/tmp/random-seed > /dev/urandom &&
  dd if=/dev/urandom of=/var/tmp/random-seed count=1 >/dev/null 2>&1
 evalret

 ainitmes "bringing up the ${cb_cyn}loopback interface${c_res}."
  ip link set up dev lo
 evalret

 ainitmes "setting the ${cb_cyn}hostname${c_res}."
  cat /etc/hostname > /proc/sys/kernel/hostname
 evalret

 ainitmes "cleaning ${cb_cyn}/tmp${c_res}."
  find /tmp -xdev -mindepth 1 ! -name lost+found -delete
 evalret

 ainitmes "restoring ${cb_cyn}alsa volume states${c_res}."
  alsactl restore >/dev/null 2>&1
 evalret

 ainitmes "setting the ${cb_cyn}console font${c_res}."
  loadfont < /usr/share/consolefonts/"${dev_font}".psf >/dev/null 2>&1
 evalret

 ainitmes "starting the ${cb_cyn}log daemons${c_res}."
  syslogd && klogd
 evalret

 ainit_nc
 ainitmes "${cb_red}services${c_res}:"; ainit_nc

 startsvcs

 for n in 1 2 3; do
  /mss/bin/sh -c "/mss/init/bin/respawn \
                   /mss/init/bin/getty /dev/tty${n} linux" &>/dev/null &
 done

 ainit_nc
}

goingdown(){
 stty onlcr; banner

 stopsvcs

 ainitmes "bringing down the ${cb_cyn}loopback interface${cb_cyn}."
  ip link set lo down >/dev/null 2>&1
 evalret

 ainitmes "saving ${cb_cyn}alsa volume states${c_res}."
  alsactl store   >/dev/null 2>&1
 evalret

 ainitmes "saving the ${cb_cyn}random seed${c_res}."
  dd if=/dev/urandom of=/var/tmp/random-seed count=1 >/dev/null 2>&1
 evalret

 ainitmes "terminating ${cb_cyn}remaining processes${c_res}."
  killall5 -s TERM && sleep 3 && killall5 -s KILL
 evalret

 ainitmes "unmounting all ${cb_cyn}mounted devices${c_res}."
  umount -f -rat nosysfs,noproc,nodevtmpfs,notmpfs >/dev/null 2>&1
 evalret
}

poweroffboi(){ goingdown && sync; sync; sync; halt -p;}
rebootboi(){   goingdown && sync; sync; sync; halt -r;}

case "${1}" in
 init)      initboi     ;;
 reboot)    rebootboi   ;;
 poweroff)  poweroffboi ;;
 *)         ainitusage "{init|reboot|poweroff}"; exit 1 ;;
esac
