#!/mss/bin/sh
# a1 >> set vars
bitsdir="/mss/init"
   sdir="${bitsdir}/services"

# a2 >> source the funcs
. "${bitsdir}"/bin/funcs

# a2 >> shut dmesg up for the love of god
dmesg --console-off

# b1 >> funcs
initboi(){
 ctrlaltdel -s; banner

 ainitmes "mounting ${c_lcyan}pseudo${c_reset} filesystems."
  ainit_mount nosuid,noexec,nodev    proc     proc /proc &&
  ainit_mount nosuid,noexec,nodev    sysfs    sys  /sys  &&
  ainit_mount defaults               tmpfs    run  /run  &&
  ainit_mount mode=0755,nosuid       devtmpfs dev  /dev  &&

  mkdir -p   /run/lock /run/shm /dev/pts &&
  chmod 1777 /run/lock /run/shm          &&
  ln    -sfn /run/shm  /dev/shm          &&

  ainit_mount gid=5,mode=620 devpts devpts /dev/pts
 evalret

 ainitmes "setting ${c_lcyan}standard streams${c_reset}."
  ln -s /proc/self/fd /dev/fd     &&
  ln -s fd/0          /dev/stdin  &&
  ln -s fd/1          /dev/stdout &&
  ln -s fd/2          /dev/stderr
 evalret

 ainitmes "starting ${c_lcyan}udev${c_reset}."
  udevd   -d                           &&
  udevadm trigger -c add -t subsystems &&
  udevadm trigger -c add -t devices    &&
  udevadm settle
 evalret

 ainitmes "remounting ${c_lcyan}rootfs${c_reset} (ro)."
  mount -o remount,ro / >/dev/null 2>&1
 evalret

 ainitmes "running ${c_lcyan}fsck${c_reset}."
  fsck -ATat noopts=_netdev >/dev/null 2>&1
 evalret

 ainitmes "remounting ${c_lcyan}rootfs${c_reset} (rw)."
  mount -o remount,rw /     >/dev/null 2>&1
 evalret

 ainitmes "mounting the entries in ${c_lcyan}fstab${c_reset}."
  mount -a                  >/dev/null 2>&1
 evalret

 ainitmes "activating ${c_lcyan}swap${c_reset}."
  swapon -a                 >/dev/null 2>&1
 evalret

 ainitmes "seeding ${c_lcyan}random${c_reset}."
  [ -f /var/tmp/random-seed ] && cat /var/tmp/random-seed > /dev/urandom &&
  dd if=/dev/urandom of=/var/tmp/random-seed count=1 >/dev/null 2>&1
 evalret

 ainitmes "bringing up the ${c_lcyan}loopback interface${c_reset}."
  ip link set up dev lo
 evalret

 ainitmes "setting the ${c_lcyan}hostname${c_reset}."
  read hname < /etc/hostname && echo "$hname" > /proc/sys/kernel/hostname
 evalret

 ainitmes "cleaning ${c_lcyan}/tmp${c_reset}."
  find /tmp -xdev -mindepth 1 ! -name lost+found -delete
 evalret

 ainitmes "utilizing ${c_lcyan}utmp${c_reset}."
  > /var/run/utmp && chmod 664 /var/run/utmp && chgrp utmp /var/run/utmp
 evalret

 ainitmes "restoring ${c_lcyan}alsa volume states${c_reset}."
  alsactl restore >/dev/null 2>&1
 evalret

 ainitmes "setting up the ${c_lcyan}console${c_reset}."
  setfont  ter-v14n -m 8859-1 && loadkeys us >/dev/null 2>&1
 evalret

 ainitmes "starting the ${c_lcyan}log daemons${c_reset}."
  syslogd -m 0 && klogd
 evalret

 ainitmes "starting ${c_lcyan}earlyoom${c_reset}."
  earlyoom -p -r 0 -M 102400,5120 -S 512000,256000 >/dev/null 2>&1 &
 evalret

 ainit_nc
 ainitmes "${c_blue}services${c_reset}:"; ainit_nc

 $sdir/thinkfan		start
 $sdir/gpm		start
 $sdir/iptables		start
 $sdir/network		start wlan0 solitude
 $sdir/mpd		start
 $sdir/dnscrypt-proxy	start
 $sdir/ntp		start
#$sdir/transmission	start
 $sdir/ssh		start

 /mss/bin/sh -c '/mss/init/bin/respawn \
                 /mss/init/bin/getty   \
                 /dev/tty1 linux' &>/dev/null &
 /mss/bin/sh -c '/mss/init/bin/respawn \
                 /mss/init/bin/getty   \
                 /dev/tty2 linux' &>/dev/null &
 /mss/bin/sh -c '/mss/init/bin/respawn \
                 /mss/init/bin/getty   \
                 /dev/tty3 linux' &>/dev/null &

 ainit_nc
}

goingdown(){
 stty onlcr; banner

 $sdir/thinkfan		stop
 $sdir/ssh		stop
 $sdir/network		stop wlan0
 $sdir/ntp		stop

 ainitmes "bringing down the ${c_lcyan}loopback interface${c_lcyan}."
  ip link set lo down >/dev/null 2>&1
 evalret

 ainitmes "saving ${c_lcyan}alsa volume states${c_reset}."
  alsactl store   >/dev/null 2>&1
 evalret

 ainitmes "saving the ${c_lcyan}random seed${c_reset}."
  dd if=/dev/urandom of=/var/tmp/random-seed count=1 >/dev/null 2>&1
 evalret

 ainitmes "terminating ${c_lcyan}remaining processes${c_reset}."
  killall5 -s TERM && sleep 3 && killall5 -s KILL
 evalret

 ainitmes "deactivating ${c_lcyan}swap${c_reset}."
  swapoff -a >/dev/null 2>&1
 evalret

 ainitmes "unmounting all ${c_lcyan}mounted devices${c_reset}."
  umount -rat nosysfs,noproc,nodevtmpfs,notmpfs >/dev/null 2>&1
 evalret
}

poweroffboi(){ goingdown && sync; sync; sync; halt -p;}
rebootboi(){   goingdown && sync; sync; sync; halt -r;}

case "${1}" in
 init)      initboi     ;;
 reboot)    rebootboi   ;;
 poweroff)  poweroffboi ;;
 *)         ainitusage "{init|reboot|poweroff}"; exit 1 ;;
esac
