#!/bin/busybox sh
/bin/busybox --install -s

export PATH="/bin:/sbin:/usr/bin:/opt/cryptshit/bin"

mount -n -t devtmpfs devtmpfs /dev
mount -n -t proc     proc     /proc
mount -n -t sysfs    sysfs    /sys
mount -n -t tmpfs    tmpfs    /run

echo 0 > /proc/sys/kernel/printk
clear

cryptsetup open /dev/sda4 x230

vgchange -ay >/dev/null 2>&1

mount /dev/apathy/rootfs /mnt

exec switch_root /mnt /mss/init/bin/init
