#!/bin/busybox sh
/bin/busybox --install bin/

export PATH="/bin:/opt/cryptshit/bin"

mount -n -t devtmpfs devtmpfs /dev
mount -n -t proc     proc     /proc
mount -n -t sysfs    sysfs    /sys
mount -n -t tmpfs    tmpfs    /run

echo 0 > /proc/sys/kernel/printk
clear

loadfont < ./font.psf >/dev/null 2>&1

printf '\n\033[1;41m%s\033[0;39m\n\n' 'initramfs (built @ REPLACEDAT)'

rshell(){
 printf '\n\e[1;31m %s\e[00m\n\n' 'you done fucked up lad, rebooting.'
 sleep 3
 exit 1
}

amachine="$(cut -d ' ' -f2,3- -O '' \
             /sys/devices/virtual/dmi/id/product_family)"

case "${amachine}" in
 X230) rawpath="/dev/sda2" rootpath="/dev/x230apathy/rootfs" ;;
  T61) rawpath="/dev/sda2" rootpath="/dev/t61apathy/rootfs"  ;;
    *) rshell                                                ;;
esac

cryptsetup open "${rawpath}" x230 || rshell

lvm vgchange -ay >/dev/null 2>&1

for i in $(cat /proc/cmdline); do
 case $i in
  resume=*)        susdev_uuid="$(echo ${i} | cut -d= -f3)" ;;
  resume_offset=*) susdev_oset="$(echo ${i} | cut -d= -f2)" ;;
 esac
done

susdev_node="$(findfs             UUID=${susdev_uuid})"
susdev_stat="$(stat -L -c '0x%t 0x%T'  ${susdev_node})"
susdev_mjmn="$(printf     '%u:%u\n'    ${susdev_stat})"

echo "${susdev_mjmn}" > /sys/power/resume
echo "${susdev_oset}" > /sys/power/resume_offset

mount "${rootpath}" /mnt

exec switch_root /mnt /mss/init/bin/init
