#!/bin/sh
# /sbin/ifup script for sysvinit
# apathy 1.2 - mssx86 (mss@waifu.club)

up(){
 if ip link show $1 > /dev/null 2>&1
  then link_status=$(ip link show $1)
   if [ -n "${link_status}" ]
    then
     if ! echo "${link_status}" | grep -q UP; then ip link set $1 up; fi
   fi

  else
   log_failure_msg "\nfailure:\ninterface ${IFACE} doesn't exist."
   exit 1
 fi
}

file=/etc/sysconfig/ifconfig.${1}

# skip backup files
[ "${file}" = "${file%""~""}" ] || exit 0

. /lib/lsb/init-functions

log_info_msg "apathy - bringing up the ${1} interface."

if [ ! -r "${file}" ]
 then
  log_failure_msg2 "\nfailure:\n${file} is missing or cannot be accessed."
  exit 1
fi

. $file

if [ "$IFACE" = "" ]
 then
  log_failure_msg2 "\nfailure:\n${file} does not define an interface [IFACE]."
  exit 1
fi

if [ "${IN_BOOT}" = "1" ] && [ ! "${ONBOOT}" = "yes" ]
 then
  log_skip_msg
  exit 0
fi

for S in ${SERVICE}
 do
  if [ ! -x "/lib/services/${S}" ]; then
   log_failure_msg "\nfailure:\nunable to process ${file}, the service ${S} was not present or cannot be executed."
   exit 1
  fi
 done

if [ "${SERVICE}" = "wpa" ]; then log_success_msg; fi

# create/configure the interface
for S in ${SERVICE}
 do
  IFCONFIG=${file} /lib/services/${S} ${IFACE} up
 done

# bring up the interface and any components
for I in $IFACE $INTERFACE_COMPONENTS; do up $I; done

# set the route default gateway if requested
if [ -n "${GATEWAY}" ]
 then
  if ip route | grep -q default; then
   log_skip_msg "apathy - gateway already setup, skipping."
  else
   log_info_msg "apathy - setting up default gateway."
   ip route add default via ${GATEWAY} dev ${IFACE}
   evaluate_retval
  fi
fi
