#!/bin/env bash
### general
# colors
clr='%{F-}'
c1='%{F#ABABAB}'
c2='%{F#E3E3E3}'
c3='%{F#747474}'
c4='%{F#6D7373}'
c5='%{F#FFFFFF}'

# separators
s1="${c4}[${clr}"
s2="${c4} | ${clr}"
s3="${c4}]${clr}"

### blocklets
while true; do
# easy blocklets
bw=$(cat /tmp/lemon-netwerk.tmp)
time=$(date '+%a %d %I:%M:%S%P')
proc=$(cat /tmp/lemon-proc.tmp)
weather=$(cat /tmp/lemon-weather.tmp)
host=$(cat /etc/hostname)
uptime=$(/home/mss/.config/scripts/uptime)

# workspace display
curr_desk=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
case ${curr_desk} in
 0) wspace="I"	;;
 1) wspace="II"	;;
 2) wspace="III";;
 3) wspace="IV"	;;
 4) wspace="V"	;;
 5) wpsace="VI"	;;
esac

# button blocklets
mpdstat="%{A:mpc next:}\
%{A2:mpc toggle > /dev/null:}\
%{A3:mpc prev > /dev/null:}\
%{A4:mpc volume +10 > /dev/null:}\
%{A5:mpc volume -10 > /dev/null:}\
$(/home/mss/.config/scripts/mpdstat)\
%{A}%{A}%{A}%{A}%{A}"

amaster="%{A3:amixer -q -D default sset Master toggle:}\
%{A4:amixer -q -D default sset Master 3dB+ unmute:}\
%{A5:amixer -q -D default sset Master 3dB- unmute:}\
$(/home/mss/.config/scripts/master-alsa)\
%{A}%{A}%{A}"

acapture="%{A3:amixer -q -D default sset Capture toggle:}\
%{A4:amixer -q -D default sset Capture 3dB+ unmute:}\
%{A5:amixer -q -D default sset Capture 3dB- unmute:}\
$(/home/mss/.config/scripts/capture-alsa)\
%{A}%{A}%{A}"

### bar
echo "%{l} ${s1}${c1}${wspace}${clr}${s3}\
%{r}${c1}${bw}${clr}${s2}\
${c2}${proc}${clr}${s2}\
${c1}${mpdstat}${clr}${s2}\
${c5}${time}${clr} \
${c3}${weather}${clr}${s2}\
${c5}${amaster} ${acapture}${clr}${s2}\
${c1}${host}${clr} \
${c3}${uptime}${clr}"
sleep 0.1
done
