#!/mss/bin/sh
# swap init script for sysvinit
# apathy 1.2 - mssx86 (mss@waifu.club)

# default-start --> S
# default-stop ---> 0 6
# description ----> mounts/umounts swap partitions defined in fstab.

. /mss/bin/apathy-funcs-init

case "${1}" in
 start)
  log_info_msg "activating all swap."
  swapon -a > /dev/null 2>&1
  evalret
 ;;

 stop)
  log_info_msg "deactivating all swap."
  swapoff -a > /dev/null 2>&1
  evalret
 ;;

 restart)
  ${0} stop
   sleep 1
  ${0} start
 ;;

 status)
  log_success_msg "retrieving swap status."
  swapon -s
 ;;

 *)
  printf "usage: ${0} {start|stop|restart|status}.\n"
  exit 1
 ;;
esac

exit 0
