.Dd February 2, 2015
.Dt RESPAWN 1
.Os ubase 0.1-apathy
.Sh NAME
.Nm respawn
.Nd spawn the given command repeatedly
.Sh SYNOPSIS
.Nm
.Op Fl l Ar fifo
.Op Fl d Ar N
.Ar cmd Op Ar args...
.Sh DESCRIPTION
.Nm
spawns the given
.Ar cmd
in a new session repeatedly.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d
Set the delay between invocations of \fIcmd\fR.  It defaults to 0.
.It Fl l
Listen on the specified
.Ar fifo
for writes. For each write spawn a new instance of
.Ar cmd .
This can be used in conjunction with a process supervisor to restart a
particular program. The
.Fl l
and
.Fl d
options are incompatible. All writes are discarded.
.El