# ps1 thingy
export PS1="\[\e[34m\][\[\e[m\]\A\[\e[34m\]]\[\e[m\] \[\e[34m\]\u\[\e[m\] \[\e[36m\]\w\[\e[m\]: "

### aliases
## program related
alias tmux="tmux -2"
alias feh="feh -d --scale-down --auto-zoom"
alias fixfuckinggpg="gpg-connect-agent updatestartuptty /bye"
alias ytm="youtube-dl -f bestaudio -x --audio-format mp3 --audio-quality 0"
## make verbose
alias ln="ln -v"
alias cp="cp -v"
alias mv="mv -v"
alias mkdir="mkdir -pv"
alias mount="mount -v"

## shortcuts
##a literal shortcuts
alias nc="ncmpcpp"
alias w="pwd"
alias s="startx --"
alias da="doas --"
alias l="ls -Askh --color=tty"
alias ll="ls -Askhw1 --color=tty"
alias lll="ls -la --color=tty"
alias grep="grep --color=auto"
alias poz="yash --posix"
##b tmux
alias td="tmux detach"
alias ta="tmux attach"
alias tk="tmux kill-session"
##c git
alias gs="git status -s"
alias gpo="git push origin master"
alias grs="git reset HEAD~1 --soft"
##d sound
alias atog="amixer set Master toggle"
alias mtog="mpc toggle"
##e transmission
alias trs="transmission-remote -n mss:mss -l"
alias tra="transmission-remote -n mss:mss -a"
##f dirs
alias cdw="cd /mss/work"
alias cdr="cd /mss/repo"
alias cds="cd /mnt/mss/stuff"
alias cda="cd /mnt/mss/stuff/media/anime"
alias cdm="cd /mnt/mss/stuff/media/music"
alias cdg="cd /mnt/mss/stuff/techy-bits/git-repositories"
alias 6c="TERM=screen-256color 6cord -c /opt/6cord/6cord.toml"
