let skip_defaults_vim=1 

set backupdir=~/.config/vim/backups
set directory=~/.config/vim/swaps

set ruler
set number

set nocompatible
set backspace=2
set mouse=

syntax on
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown

colorscheme elflord

inoremap <C-h> <Left>
inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-l> <Right>
cnoremap <C-h> <Left>
cnoremap <C-j> <Down>
cnoremap <C-k> <Up>
cnoremap <C-l> <Right>
