let skip_defaults_vim=1 

set backupdir=~/.config/vim/backups
set directory=~/.config/vim/swaps

set nocompatible
set mouse=

set ruler
set number
set backspace=indent,eol,start
set laststatus=2
set colorcolumn=80

syntax on
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown

colorscheme industry

inoremap <C-h> <Left>
inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-l> <Right>
cnoremap <C-h> <Left>
cnoremap <C-j> <Down>
cnoremap <C-k> <Up>
cnoremap <C-l> <Right>
