#!/mss/bin/sh
. /mss/bin/apathy-init-funcs

case "$1" in
 start)

  ainitmes "mounting /run"
   if ! mountpoint /run >/dev/null;  then mount /run; fi &&
   mkdir -p /run/lock /run/shm                           &&
   chmod 1777 /run/shm /run/lock
  evalret

  ainitmes "mounting /proc"
   if ! mountpoint /proc >/dev/null; then mount -o nosuid,noexec,nodev /proc; fi
  evalret

  ainitmes "mounting /sys"
   if ! mountpoint /sys >/dev/null;  then mount -o nosuid,noexec,nodev /sys; fi
  evalret

  ainitmes "mounting /dev"
   if ! mountpoint /dev >/dev/null;  then mount -o mode=0755,nosuid /dev; fi
  evalret

  ln -sfn /run/shm /dev/shm  
 ;;
 *)
  ainitusage "{start}"
  exit 1
 ;;
esac
