#!/mss/bin/sh
. /mss/bin/apathy-init-funcs

#    unmounting all mounted devices.
#  w exited with 32, probably ran stripper.
#  f mounting rootfs in ro mode.
#    /etc/apathy-init/scripts/mountfs exited with 32.
#    continue anyway? (y/n): n


case "${1}" in
 start)
  ainitmes "remounting the ${c_lcyan}rootfs${c_reset} in ${c_lcyan}ro${c_reset} mode."
   mount --options remount,rw /      >/dev/null 2>&1
  evalret

  mkdir -p /dev/pts

  ainitmes "mounting the entries in ${c_lcyan}fstab${c_reset}."
   mount --all --test-opts no_netdev >/dev/null 2>&1
  evalret
 ;;
 stop)
  ainitmes "unmounting all ${c_lcyan}mounted devices${c_reset}."
   losetup -D
   umount --all --detach-loop --read-only \
    --types notmpfs,nosysfs,nodevtmpfs,noproc,nodevpts \
    >/dev/null 2>&1

   umountexit1="${?}"

   if [ "${umountexit1}" -eq "32" ]
    then
     warnprompt; ainitmes "exited with 32, probably ran ${c_lcyan}stripper${c_reset}."
     warnprompt
    else
     exit "${umountexit1}"; evalret
   fi

  ainitmes "mounting ${c_lcyan}rootfs${c_reset} in ${c_lcyan}ro${c_reset} mode."
   mount --options remount,ro /      >/dev/null 2>&1

   umountexit2="${?}"

   if [ "${umountexit2}" -eq "32" ]
    then
     warnprompt; ainitmes "exited with 32, probably ran ${c_lcyan}stripper${c_reset}."
     warnprompt
    else
     exit "${umountexit2}"; evalret
   fi
 ;;
 *)
  ainitusage "{start|stop}"
  exit 1
 ;;
esac
