#!/mss/bin/sh
. /mss/bin/apathy-init-funcs

ifacelist=$(awk '{gsub(":",""); print $1}' /proc/net/dev \
            |grep -v -e 'Inter' -e 'face' -e 'lo')

case "${ifacelist}" in
 *wlan0*)
  IFACE="wlan0"
  WPACONFIG=/etc/wpa_supplicant/mssNetwork.conf
 ;;
 *)
  if [ -z "$(grep "eth0" /proc/net/dev)" ]
   then
    ainitmes "wlan0 or eth0 does not exist.";   failprompt
    ainitmes "not connecting to the internet."; failprompt
    exit 1
   else
    IFACE="eth0"
  fi
 ;;
esac

IP=192.168.1.31
GATEWAY=192.168.1.1
PREFIX=24
BROADCAST=192.168.1.99

case "${1}" in
 start)
  if [ "${IFACE}" = "wlan0" ]
   then
    ainitmes "connecting wlan0 to wlan via wpa_supplicant" 
     wpa_supplicant -B -i "${IFACE}" -c "${WPACONFIG}" >/dev/null 2>&1
    evalret
  fi

   ainitmes "adding ${IP} to ${IFACE}."
    ip addr add "${IP}"/"${PREFIX}" broadcast "${BROADCAST}" dev "${IFACE}"
   evalret

   ainitmes "bringing the interface up."
    ip link set ${IFACE} up
   evalret

   ainitmes "setting up the default gateway."
    ip route add default via ${GATEWAY} dev ${IFACE}
   evalret
 ;;
 stop)
  if [ "${IFACE}" = "wlan0" ]
   then
    ainitmes "killing wpa_supplicant."
     kill -TERM $(pidof wpa_supplicant) >/dev/null 2>&1
    evalret
  fi

  ainitmes "removing ${IP} from ${IFACE}."
   ip addr del "${IP}"/"${PREFIX}" broadcast "${BROADCAST}" dev "${IFACE}"
  evalret

 #ainitmes "removing default gateway."
 # ip route del default >/dev/null 2>&1
 #evalret

  ainitmes "bringing ${IFACE} down."
   ip link set ${IFACE} down
  evalret
 ;;
 restart)
  ${0} stop; sleep 1; ${0} start
 ;;
 *)
  ainitusage "{start|stop|restart}"
  exit 1
 ;;
esac
