#!/mss/bin/sh
. /mss/bin/apathy-init-funcs

case "$1" in
 stop)
  ainitmes "sending ${c_lcyan}TERM${c_reset} to all processes."
   killall5 -15
  evalret

  sleep 3

  ainitmes "sending ${c_lcyan}KILL${c_reset} to remaining processes."
   killall5 -9
  evalret
 ;;
*)
  ainitusage "{stop}"
  exit 1
 ;;
esac
