#!/mss/bin/sh
. /mss/bin/apathy-init-funcs

case "$1" in
 stop)
  ainitmes "sending TERM to all processes."
   killall5 -15
  evalret

  sleep 3

  ainitmes "sending KILL to remaining processes."
   killall5 -9
  evalret
 ;;
*)
  ainitusage "{stop}"
  exit 1
 ;;
esac
