#!/mss/bin/sh
. /mss/bin/apathy-init-funcs

case "$1" in
 start)
  ainitmes "starting the system log daemon."
   syslogd -m 0
  evalret

  ainitmes "starting the kernel log daemon."
   klogd
  evalret
 ;;
 stop)
  ainitmes "stopping the kernel log daemon."
   local pid="$(pidof klogd)"
   if [ -z "$pid" ]
    then failprompt; ainitmes "klogd is not running."; failprompt
    else kill -TERM "${pid}"; evalret
   fi

  ainitmes "stopping the system log daemon."
   local pid="$(pidof syslogd)"
   if [ -z "$pid" ]
    then failprompt; ainitmes "syslogd is not running."; failprompt
    else kill -TERM "${pid}"; evalret
   fi
 ;;
 *)
  ainitusage "{start|stop|restart}"
  exit 1
 ;;
esac
