#!/mss/bin/sh
. /mss/initbits/bin/apathy-init-funcs

# a1 >> set vars
sdir="/mss/initbits/scripts"
initver="sinit-1.1-apathy"
curdate="$(date '+%a %d %I:%M:%S%P' | awk '{print tolower($1),$2,$3}')"
curkern="$(uname -r)"

# a2 >> shut dmesg up for the love of god
dmesg --console-off

# a3 >> trap signals that may kill rc
trap "" INT QUIT TSTP

# b1 >> funcs
printlogo(){
 ainit_nc
 ainitmes "${c_red}   __,  ,_   __,  -/- /_";     ainit_nc
 ainitmes " (_/(__/_)_(_/(__/__/ (__(_/_";        ainit_nc
 ainitmes "      /                  _/_";         ainit_nc
 ainitmes "     /                  (/${c_reset}"; ainit_nc
 ainit_nc
}

welcome(){
 clear; printlogo

 ainitmes "welcome to ${c_blue}apathy ${c_red}musl ${c_green}1.2${c_reset}."; ainit_nc
 ainitmes "running on kernel ${c_green}${curkern}${c_reset}.";                ainit_nc
 
 ainit_nc
 ainitmes "${c_green}${curdate}${c_reset} - ${c_green}${initver}${c_reset}";  ainit_nc
 ainit_nc
}

goodbye(){
 clear; printlogo

 ainitmes "shutting ${c_blue}apathy ${c_red}musl ${c_green}1.2${c_reset} down."; ainit_nc
 ainit_nc
}

initboi(){
 /bin/ash /mss/initbits/config/term-colors.conf
 welcome

 /mss/initbits/bin/ctrlaltdel -s

 $sdir/mountvirtfs	start || /bin/ash
 $sdir/localnet		start
 $sdir/udev		start

 cd /dev
 ln -sf /proc/self/fd/0  stdin
 ln -sf /proc/self/fd/1  stdout
 ln -sf /proc/self/fd/2  stderr
 cd - 1>/dev/null

 $sdir/swap		start
 $sdir/checkfs		start
 $sdir/mountfs		start
 $sdir/setsched		start
 $sdir/cleanfs		start
 $sdir/alsa		start
 $sdir/console		start

 $sdir/sysklogd		start
 $sdir/iptables		start
 $sdir/network		start
 $sdir/random		start
 $sdir/gpm		start
 $sdir/mpd		start
 $sdir/dnscrypt-proxy	start
#$sdir/ssh		start

 : > /var/run/utmp

 /mss/bin/sh -c '/mss/initbits/bin/respawn \
                 /mss/initbits/bin/getty   \
                 /dev/tty1 linux' &>/dev/null &
 /mss/bin/sh -c '/mss/initbits/bin/respawn \
                 /mss/initbits/bin/getty   \
                 /dev/tty2 linux' &>/dev/null &
 /mss/bin/sh -c '/mss/initbits/bin/respawn \
                 /mss/initbits/bin/getty   \
                 /dev/tty3 linux' &>/dev/null &
}

poweroffboi(){
 goodbye

 $sdir/gpm		stop
 $sdir/mpd		stop
 $sdir/dnscrypt-proxy	stop
#$sdir/ssh		stop
 $sdir/alsa		stop
 $sdir/random		stop
 $sdir/network		stop
 $sdir/sysklogd		stop
 $sdir/sendsignals	stop
 $sdir/swap		stop
 $sdir/mountfs		stop
 $sdir/localnet		stop

 /mss/initbits/bin/sync
 sleep 3
 /mss/initbits/bin/halt -p
}

rebootboi(){
 goodbye

 $sdir/gpm		stop
 $sdir/mpd		stop
 $sdir/dnscrypt-proxy	stop
#$sdir/ssh		stop
 $sdir/alsa		stop
 $sdir/random		stop
 $sdir/network		stop
 $sdir/sysklogd		stop
 $sdir/sendsignals	stop
 $sdir/swap		stop
 $sdir/mountfs		stop
 $sdir/localnet		stop

 /mss/initbits/bin/sync
 sleep 3
 /mss/initbits/bin/halt -r
}

case "${1}" in
 init)      initboi     ;;
 reboot)    rebootboi   ;;
 poweroff)  poweroffboi ;;
 *)         ainitusage "{init|reboot|poweroff}"; exit 1 ;;
esac
