#!/bin/env bash

### ascii ###
cat /usr/local/bin/ascii

### functions ###
# sed delete last line
del_col (){
 sed -r 's/\s+\S+$//'
}
# lowercase
lcs (){
tr '[:upper:]' '[:lower:]'
}

### good stuff ###
# distro 
if [ -f "/etc/lsb-release" ]
then
 dist=$(grep "ID" "/etc/lsb-release" \
	| sed 's/DISTRIB_ID\=//g' \
	| sed 's/\"//g')

else
 dist=$(grep "NAME" "/etc/os-release" | head -1 | sed 's/NAME=//g')
fi

# cpu model
cpu=$(lscpu \
	| grep "Model name" \
	| sed 's/Model name:          //g' \
	| sed 's/CPU //g' \
	| del_col \
	| del_col \
	| cut -f1 -d" " --complement)
# freq
freq_old=$(lscpu \
	| grep "CPU MHz:" \
	| sed 's/CPU MHz:             //g' \
	| sed 's/[.].*$//')
freq=$(echo ${freq_old} / 1000 \
	| bc -l \
	| cut -c-5)
# kernel
kern=$(uname -r)

# uptime
upt=$(uptime --pretty \
	| sed 's/up //' \
	| sed 's/\ years\?,/y/' \
	| sed 's/\ days\?,/d/' \
	| sed 's/\ hours\?,\?/h/' \
	| sed 's/\ minutes\?/m/')

# memory
tot=$(free -h | head -2 | tail -1 | awk '{print $2}' | sed 's/Gi//g')
use=$(free -h | head -2 | tail -1 | awk '{print $3}' | sed 's/Gi//g')

### echo ###
echo " [*] dist: ${dist}"
echo " [*] kern: ${kern}"
echo " [*] sh  : $SHELL"
echo " [*] upt : ${upt}"
echo " [*] cpu : ${cpu} @ ${freq}GHz" 
echo " [*] mem : ${use}/${tot}G" 
echo 
