#!/bin/env bash
#root check
if [ "$(id -u)" -ne 0 ]; then
	echo ' ! this script must be run by root.' >&2
	exit 1
fi

echo " * running /usr/sbin/make-ca -g." &&
/usr/sbin/make-ca -g > /dev/null 2>&1 && echo " ** done" &&

echo " * running /usr/sbin/update-pciids." &&
/usr/sbin/update-pciids > /dev/null 2>&1 && echo " ** done" &&

echo " * running /usr/sbin/ntpd -q -g." &&
/usr/sbin/ntpd -q -g > /dev/null 2>&1 && echo " ** done" &&

echo " * running the usbutils thingy" &&
/usr/bin/wget http://www.linux-usb.org/usb.ids -o /usr/share/hwdata/usb.ids > /dev/null 2>&1 && echo " * done" && echo &&

echo " ** system is up to date."
