CC=gcc CXX=g++ meson \
	--prefix=/usr                   \
        -Dbuildtype=release             \
        -Ddri-drivers=i915,i965,swrast  \
        -Dgallium-drivers=              \
        -Dgallium-nine=false            \
        -Dgallium-extra-hud=false       \
        -Dgallium-vdpau=false           \
        -Dgallium-xvmc=false            \
        -Dgallium-omx=disabled          \
        -Dgallium-va=false              \
        -Dgallium-xa=false              \
        -Dgallium-opencl=disabled       \
        -Dvulkan-drivers=               \
        -Dglx=dri                       \
        -Db_lto=false                   \
        -Dplatforms=x11,drm             \
        -Ddri3=true                     \
        -Dllvm=false                    \
        -Dosmesa=classic                \
        -Dvalgrind=false                \
        ..
