// msslinux useragent
pref("general.useragent.override", "Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0");

// privacy
pref("extensions.blocklist.enabled", false);
pref("services.sync.prefs.sync.security.OCSP.enabled", false);
pref("security.OCSP.GET.enabled", false);
pref("security.OCSP.require", false);
pref("security.OCSP.enabled", 0);
pref("geo.enabled", false);
