#!/mss/bin/sh
. /mss/bin/apathy-funcs

aprint_nc
aprint "input the links you want to have downloaded: "
dd if=/dev/stdin of=/tmp/links.tmp >/dev/null 2>&1

links="$(cat /tmp/links.tmp)"

if [ -z "${links}" ]
 then
  aprint_nc
  aprint_fail "no links are given, exiting."
  aprint_nc
  exit 1
 else
  aprint_nc
  aprint "specified links are: "
  for penis in $links; do aprint_nm "$penis"; done
  aprint_nc
fi

echo "${links}" | /mss/bin/a2norpc -i -
