#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

if   [ -z "$1" ]; then aprint_fail "no mount point selected, exiting."; exit 1
elif [ -z "$2" ]; then aprint_fail "no user selected, exiting.";        exit 1
fi

aprint_nc

aprint_ret "allowing all connections to X."
 xhost + > /dev/null 2>&1
evalretkill

aprint_ret "mounting."
 mount --bind "$1" "$1"                    &&
 mount -t proc /proc "$1"/proc             &&
 mount --make-rslave --rbind /sys "$1"/sys &&
 mount --make-rslave --rbind /dev "$1"/dev &&
 mount --make-rslave --rbind /run "$1"/run
evalretkill

aprint "chrooting to ${c_lcyan}$1${c_reset} as user ${c_lcyan}$2${c_reset}."
aprint_nc
 chroot "$1"         \
  /bin/env -i        \
   HOME=/home/mss    \
   TERM="$TERM"      \
   PS1='[chroot] : ' \
   DISPLAY=:0        \
   PATH=/bin:/usr/bin:/sbin:/usr/sbin \
    /bin/su - $2

aprint_nc
aprint_ret "exited chroot, unmounting."
 umount -l "$1"/proc &&
 umount -l "$1"/sys  &&
 umount -l "$1"/dev  &&
 umount -l "$1"/run  &&
 umount -l "$1" 
evalretkill

aprint_ret "reverting xhost perms."
 xhost - > /dev/null 2>&1
evalretkill

aprint_nc
