#!/mss/bin/sh
if	[ "$(id -u)" -ne 0 ];	then printf "\n ! this script must be run by root, exiting.\n\n";	exit 1
elif	[ -z "$1" ];		then printf "\n ! no mount point selected, exiting.\n\n";		exit 1
fi

printf " * allowing all connections to X.\n" && xhost + &&
printf " * mounting.\n" &&
 mount --bind "$1" "$1" &&
 mount -t proc /proc "$1"/proc &&
 mount --make-rslave --rbind /sys "$1"/sys &&
 mount --make-rslave --rbind /dev "$1"/dev &&
 mount --make-rslave --rbind /run "$1"/run &&
printf " * mounted, chrooting.\n" && chroot "$1" /bin/bash
printf " * exited chroot, umounting.\n" &&
 umount -l "$1"/{proc,sys,dev,run} &&
 umount -l "$1" &&
printf " * umounted successfully.\n" &&
printf " * reverting xhost perms.\n" && xhost - && printf " * done.\n"
