#!/mss/bin/sh
if [ "$(id -u)" -ne 0 ]; then printf "\n ! this script must be run by root, exiting.\n\n"; exit 1; fi

rm -rfv  /var/log/Xorg*

printf '' > /var/log/auth.log
printf '' > /var/log/boot.log
printf '' > /var/log/daemon.log
printf '' > /var/log/iptables.log
printf '' > /var/log/kern.log
printf '' > /var/log/lastlog
printf '' > /var/log/mail.log
printf '' > /var/log/sys.log
printf '' > /var/log/user.log

printf '' > /var/run/bootlog
printf " * done.\n"
