#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

rm -rfv  /var/log/Xorg*

printf '' > /var/log/auth.log
printf '' > /var/log/boot.log
printf '' > /var/log/daemon.log
printf '' > /var/log/iptables.log
printf '' > /var/log/kern.log
printf '' > /var/log/lastlog
printf '' > /var/log/mail.log
printf '' > /var/log/sys.log
printf '' > /var/log/user.log

printf '' > /var/run/bootlog
printf " * done.\n"
