#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

cd /var/log

for log in *
 do
  if [ -f "${log}" ]
   then
    aprint_ret "cleaning ${c_lcyan}${log}${c_reset}." 
    printf '' > "${log}"
    evalret
   else
    aprint_fail "${c_lcyan}${log}${c_reset} is a directory."
  fi
 done

aprint_ret "cleaning ${c_lcyan}/var/lib/mpd/log${c_reset}."
printf '' > /var/lib/mpd/log
evalret
