#!/mss/bin/sh
. /mss/bin/apathy-funcs

aprint_ret "${c_red}
  __,  ,_   __,  -/- /_
 (_/(__/_)_(_/(__/__/ (__(_/_
      /                  _/_
     /                  (/${c_reset}\n"
aprint_nc

dist=$(awk 'gsub("DISTRIB_ID=", ""),gsub("\"", "")' /etc/lsb-release)
read model < /sys/devices/virtual/dmi/id/product_name
read _host < /etc/hostname
cpu=$(awk '/model name/ {print $5,$7}' /proc/cpuinfo | tail -1)
freq=$(awk '/MHz/ {print int($4)"mhz"}' /proc/cpuinfo | tail -1)
kern_pre=$(uname -r)
kern="${kern_pre%%-*} (${kern_pre#*-})"
_binsh="$(file /bin/sh | awk '{gsub(" symbolic link to",""); sub(/\/bin\//, "", $2) }1')"
_sh="$(basename $SHELL) $($SHELL --version | awk 'NR==1 {print $5}') (${_binsh})"
upt=$(uptime --pretty | sed 's/up //;s/\ days\?,/d/;s/\ hours\?,\?/h/;s/\ minutes\?/m/')
mem=$(free --mebi | awk 'NR==2 {print $3"/"$2"mib"}')

lsdetail "os"   "${dist}"
lsdetail "kern" "${kern}"
lsdetail "host" "${_host} (${model})"
lsdetail "sh"   "${_sh}"
lsdetail "cpu"  "${cpu} @ ${freq}"
lsdetail "mem"  "${mem}"
lsdetail "upt"  "${upt}"
aprint_nc
