#!/mss/bin/sh
. /mss/bin/apathy-funcs

printlogo(){
aprint_ret "${cb_red}
  __,  ,_   __,  -/- /_
 (_/(__/_)_(_/(__/__/ (__(_/_
      /                  _/_
     /                  (/${c_res}\n"
}

dist=$(awk '/PRETTY_NAME/{gsub(/PRETTY_NAME=\"|\"/,""); print}' /etc/os-release)
 cpu=$(awk '/model name/{family=$5; model=$8}; /MHz/{hz=int($4)}; END{print family, model, "@", hz"mhz"}' /proc/cpuinfo)

read model < /sys/devices/virtual/dmi/id/product_family
read _host < /etc/hostname

kern_pre=$(uname -r)
    kern="${kern_pre%%-*} (${kern_pre#*-})"

usershell=$(basename $(grep $LOGNAME /etc/passwd | cut -d: -f7))
    binsh=$(realpath /bin/sh | awk 'sub(/\/bin\//,"")')
    shell="$usershell $($usershell --version | awk 'NR==1 {ver=$5}; END{print ver}') (/bin/sh: ${binsh})"

mem=$(awk '/Avail/    {avail=int($2/1024)};     \
           /MemTotal/ {total=int($2/1024)};     \
           END{print (total-avail)"/"total"m"}' \
           /proc/meminfo)

upt_pre=$(awk '{print int($1)}' /proc/uptime)

   [ "${upt_pre}" -lt 3600  ]                   \
&& upt=$(printf "%02d:%02.0f\n"                 \
                 "$(((${upt_pre}%3600)/60))"    \
                 "$((${upt_pre}%60))")          \
|| [ "${upt_pre}" -lt 86400 ]                   \
&& upt=$(printf "%02d:%02d:%02.0f\n"            \
                 "$(((${upt_pre}%86400)/3600))" \
                 "$(((${upt_pre}%3600)/60))"    \
                 "$((${upt_pre}%60))")          \
|| upt=$(printf "%d:%02d:%02d:%02.0f\n"         \
                 "$((${upt_pre}/86400))"        \
                 "$(((${upt_pre}%86400)/3600))" \
                 "$(((${upt_pre}%3600)/60))"    \
                 "$((${upt_pre}%60))")

printlogo; aprint_nc
lsdetail "os"   "${dist}"
lsdetail "kern" "${kern}"
lsdetail "host" "${cb_blk}${_host}${c_res} on ${cb_blu}${model}${c_res}"
lsdetail "sh"   "${shell}"
lsdetail "cpu"  "${cpu}"
lsdetail "mem"  "${mem}"
lsdetail "upt"  "${upt} ($upt_pre)"
aprint_nc
