#!/mss/bin/sh
. /mss/bin/apathy-funcs

if [ -z $1 ]
 then
  aprint_nc
  aprint_fail "no output dir selected at ${cl_grn}\$1${c_res}."
  aprint_nc
  exit 1
 else
  ffmpeg \
   -f x11grab -r 25 -s 1366x768 -i :0.0 \
   -f alsa -ac 2 -i hw:0                \
   "$1".mkv
fi
