#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

curr_dns="$(cat /etc/resolv.conf | tail -1)"
aprint_nc

case "${curr_dns}" in
 *edns0*)
  aprint "using dnscrypt."
  aprint_ret "stopping dnscrypt."
  /etc/init.d/dnscrypt-proxy stop > /dev/null 2>&1
  evalretkill

  aprint_ret "replacing ${c_lcyan}resolv.conf${c_reset}."
  cp /etc/resolv.conf.quad /etc/resolv.conf
  evalretkill
  
  aprint_ret "setting clock."
  ntpd -q -g > /dev/null 2>&1
  evalretkill

  aprint_ret "placing the ${c_lcyan}dnscrypt resolv.conf${c_reset} back."
  cp /etc/resolv.conf.dnscrypt /etc/resolv.conf
  evalretkill

  aprint_ret "starting dnscrypt back."
  /etc/init.d/dnscrypt-proxy start > /dev/null 2>&1
  evalretkill
  ;;
 *)
  aprint "not using dnscrypt."
  aprint_ret "setting clock."
  ntpd -q -g > /dev/null 2>&1
  evalretkill
  ;;
esac
aprint_nc
