#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

currdns=$(cat /etc/resolv.conf | tail -1)
case $currdns in
 *edns0*)
  printf "using dnscrypt.\n"				&&
  /etc/init.d/dnscrypt-proxy stop			&&
  cp -v /etc/resolv.conf /etc/resolv.conf.dnscrypt	&&
  cp -v /etc/resolv.conf.flare /etc/resolv.conf		&&
  ntpd -q -g > /dev/null 2>&1				&&
  cp -v /etc/resolv.conf.dnscrypt /etc/resolv.conf	&&
  /etc/init.d/dnscrypt-proxy start			&&
  printf "done.\n"
  ;;
 *)
  printf "not using dnscrypt.\n"			&&
  ntpd -q -g > /dev/null 2>&1				&&
  printf "done.\n"
  ;;
esac

exit 0
