#!/mss/bin/sh
if [ -z "$1" ]
 then stats=$(curl -s "https://tools.keycdn.com/geo.json" | jq '.data | .geo | .[]' | sed 's/\"//g')
 else stats=$(curl -s "https://tools.keycdn.com/geo.json?host=$1" | jq '.data | .geo | .[]' | sed 's/\"//g')
fi

pstat(){ printf "$stats" ;}

mhost=$(pstat | awk 'NR==1')
mipad=$(pstat | awk 'NR==2')
mrdns=$(pstat | awk 'NR==3')
mispa=$(pstat | awk 'NR==5')
mcont=$(pstat | awk 'NR==12')
mcity=$(pstat | awk 'NR==10')
mtime=$(pstat | awk 'NR==17')
mcoun=$(pstat | awk 'NR==6')
mpost=$(pstat | awk 'NR==11')
mdate=$(pstat | awk 'NR==18')
mcode=$(pstat | awk 'NR==7')

printf "\n * ip   \t: $mipad\n * host \t: $mhost\n * rdns \t: $mrdns\n * isp  \t: $mispa\n * country \t: $mcoun ($mcode) ($mcont)\n * city \t: $mcity ($mpost)\n * timezone\t: $mtime ($mdate)\n\n"
