#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

if   [ ! -f $PWD/arch/x86/boot/bzImage ]; then aprint_fail "${cl_grn}bzImage${c_res} doesn't exist."; exit 1
elif [ ! -f $PWD/System.map ];            then aprint_fail "${cl_grn}System.map doesn't exist.";        exit 1
elif [ ! -f $PWD/.config ];               then aprint_fail "kernel ${cl_grn}.config doesn't exist.";    exit 1
fi


aprint_nc
aprint     "this action will replace the existing kernel."
aprint_ask "shall we proceed? (y/n): "

read answer

if [ "$answer" != "${answer#[Yy]}" ]
 then
  aprint_ret "copying ${cl_grn}bzImage${c_res} to ${cl_grn}/boot/vmlinuz${c_res}."
  cp arch/x86/boot/bzImage /boot/vmlinuz
  evalretkill

  aprint_ret "copying ${cl_grn}System.map${c_res} to ${cl_grn}/boot/System.map${c_res}."
  cp System.map /boot/System.map
  evalretkill

  aprint_ret "copying kernel ${cl_grn}config${c_res} to ${cl_grn}/boot/config${c_res}."
  cp .config /boot/config
  evalretkill
  aprint_nc
 else
  aprint "aborting"
  exit 1
fi
