#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

if [ ! -e $PWD/arch/x86/boot/bzImage ]; then printf "\n ! bzImage doesn't exist, exiting.\n\n"; exit 1
elif [ ! -e $PWD/System.map ]; then printf "\n ! System.map doesn't exist, exiting.\n\n"; exit 1
elif [ ! -e $PWD/.config ]; then printf "\n ! kernel .config doesn't exist, exiting.\n\n"; exit 1
fi

cp -iv arch/x86/boot/bzImage	/boot/vmlinuz		&&
cp -iv System.map		/boot/System.map	&&
cp -iv .config			/boot/config		&&
printf " * done.\n"
