#!/mss/bin/sh
dat=$(date "+%Y-%m-%d_%I-%M-%S%P_maimscrot")
loc="/home/mss/screenshots/entire/${dat}.png"

if [ -z "$1" ]
 then
  savloc="${loc}"
  maim -u > "${loc}"
 else
  savloc="${1}"
  maim -u > "${1}"
fi

aprint_nc
aprint "screen grabbed to ${cb_grn}${savloc}${c_res}."
aprint_nc
