#!/mss/bin/sh
dat=$(date "+%Y-%m-%d_%I-%M-%S%P_maimcrop")
loc="/home/mss/screenshots/grabs/${dat}.png"

if [ -z "$1" ]
 then
  savloc="${loc}"
  maim -s -u > "${loc}"

  local error_value="${?}"
  [ ! "${error_value}" = 0 ] && rm -rfv "${savloc}"

 else
  savloc="$1"
  maim -s -u > "${1}"

  local error_value="${?}"
  [ ! "${error_value}" = 0 ] && rm -rfv "${savloc}"
fi

aprint_nc
aprint "grab saved to ${cb_grn}${savloc}${c_res}."
aprint_nc
