#!/mss/bin/sh
. /mss/bin/apathy-funcs

localraw="/mss/raw-packages.txt"
reporaw="/mss/repo/pkg-management/raw-packages.txt"
localmd="/mss/packages.md"
repomd="/mss/repo/pkg-management/packages.md"

case $1 in
 sync)
   aprint_ret "${c_lcyan}(repo -> local)${c_reset}\tsyncing ${c_lcyan}raw-packages.txt${c_reset}."
    cp /mss/repo/pkg-management/raw-packages.txt /mss/raw-packages.txt
   evalret

   aprint_ret "${c_lcyan}(repo -> local)${c_reset}\tsyncing ${c_lcyan}packages.md${c_reset}."
    cp /mss/repo/pkg-management/packages.md      /mss/packages.md
   evalret
   exit 0
 ;;
 convert)
  if [ ! -f "${repomd}" ]
   then
    aprint_fail "${c_lcyan}(repo)${c_reset}${c_lcyan}packages.md${c_reset} not found."
    exit 1
   else
    aprint "${c_lcyan}(repo)\t\t${c_reset}converting ${c_lcyan}packages.md${c_reset} to ${c_lcyan}raw-packages.txt${c_reset}."
    grep -v -e \# -e \` -e \! "${repomd}" | awk '/\[d\]/ {print $4}' > "${reporaw}"
  fi
 ;;
 r|removed)
  if [ ! -f "${localmd}" ]
   then
    aprint_fail "${c_lcyan}(local)${c_reset}\t\t${c_lcyan}packages.md${c_reset} is missing." 
    exit 1
   else
    aprint "${c_lcyan}(local)${c_reset}\t\tremoved packages are: "
    awk '/^\[r/{printf ("%s\t\t%s\n", $2, $4)}' "${localmd}"
  fi
 ;;
 d|installed)
  if [ ! -f "${localmd}" ]
   then
    aprint_fail "${c_lcyan}(local)${c_reset}\t\t${c_lcyan}packages.md${c_reset} is missing." 
    exit 1
   else
    aprint "${c_lcyan}(local)${c_reset}\t\tinstalled packages are: "
    awk '/^\[d/{printf ("\t%s\t\t%s\n", $2, $4)}' "${localmd}"
  fi
 ;;
 o|ondemand)
  if [ ! -f "${localmd}" ]
   then
    aprint_fail "${c_lcyan}(local)${c_reset}\t\t${c_lcyan}packages.md${c_reset} is missing." 
    exit 1
   else
    aprint "${c_lcyan}(local)${c_reset}\t\tondemand packages are: "
    awk '/^\[o/{printf ("\t%s\t\t%s\n", $2, $4)}' "${localmd}"
  fi
 ;;
 stats|*)
  tsize="$(df --block-size=KiB / | awk 'NR==2 {print $3/1024"mib"}')"

  if [ ! -f "${localmd}" ]
   then
    rcount="l${c_lcyan}(local)\t\t${c_lcyan}packages.md${c_reset} is missing."
    ondemand="${c_green}(${c_reset}none${c_green})${c_reset}"
   else
    rcount=$(grep "\[r\]" "${localmd}" | wc -l)
    ocount=$(grep "\[o\]" "${localmd}" | wc -l)
    ondemand="${c_green}(${c_blue}+${c_reset}${ocount}${c_green})${c_reset}"
  fi

  if [ ! -f "${localraw}" ]
   then count="${c_lcyan}(local)\t\t$raw-packages.txt${c_reset} is missing."
   else count=$(awk 'END{print NR}' "${localraw}")
  fi
  
  if [ ! -d "/mss/repo" ]
   then
    gitstat="${c_lcyan}(repo)\t\t/mss/repo${c_reset} is missing."
   else
    gitstat_pre=$(cd /mss/repo && git status -s)
  
    if [ -z "$gitstat_pre" ]
     then gitstat="clean."
     else gitstat="\n\n$gitstat_pre"
    fi
  fi
  
  if [ ! -f "${localraw}" ] || [ ! -f "${reporaw}" ]
   then
    gitdf="${c_lcyan}(local, repo)${c_reset}\t${c_lcyan}raw-packages.txt${c_reset} is missing."
   else
    gitdf_pre=$(diff -u "${localraw}" "${reporaw}"                       \
                 | awk '/^---/   {print "- local"" --->",$3"\t"$4};      \
                        /^\+\+\+/ {print "+ git"" ----->",$3"\t"$4"\n"}; \
                        /^\+[a-z,0-9]/;                                  \
                        /^-[a-z,0-9]/')
    
    if [ -z "$gitdf_pre" ]
     then gitdf="none."
     else gitdf=$(printf "\n\n$gitdf_pre\n")
    fi
  fi

 aprint_nc
 aprint "${c_green}total partition size\t${c_blue}:${c_reset} ${tsize}"
 aprint "${c_green}local package count\t${c_blue}:${c_reset} ${count} ${ondemand}"
 aprint "${c_green}removed packages\t${c_blue}:${c_reset} ${rcount}"
 aprint "${c_green}local and git diff\t${c_blue}:${c_reset} ${gitdf}"
 aprint "${c_green}git repo status\t${c_blue}:${c_reset} ${gitstat}"
 aprint_nc
 ;;
esac
