#!/mss/bin/sh
. /mss/bin/apathy-funcs

if	[ -z $1 ]; then aprint_fail "no dir or file to pkgup selected in \$1, exiting."; exit 1
elif	[ -z $2 ]; then aprint_fail "no archive name in \$2 specified, exiting."; exit 1
fi

if	[ -d $1 ]; then aprint "pkgtype is ${c_lcyan}dir${c_reset}."
elif	[ -f $1 ]; then aprint "pkgtype is ${c_lcyan}file${c_reset}."
else	aprint_fail "pkgtype not understood or does not exist, exiting."; exit 1
fi

tar -cf - ${1} | xz -9e --threads=2 --verbose -c - > ${2}.tar.xz
