#!/mss/bin/sh
. /mss/bin/apathy-funcs

triplet=$(gcc -dumpmachine)
ccver=$(gcc -v 2>&1 | awk '/version / {sub(/version /,""); print}')
init="sinit 1.1 (apathy)"
tls=$(openssl version | awk '{print tolower($0)}')

case ${triplet} in
 *gnu*)  libc="glibc $(ldd --version | awk '/libc/ {print $4}')" ;;
 *musl*) libc="musl $(ldd 2>&1 | awk '/Version/ {print $2}')"    ;;
esac

aprint_nc
lsdetail "init" "${init}"
lsdetail "tls"  "${tls}"
lsdetail "libc" "${libc} ($(uname -m))"
lsdetail "trpl" "${triplet}"
lsdetail "cc"   "${ccver}"
aprint_nc
