#!/mss/bin/sh
. /mss/bin/apathy-funcs

[ ! "${TERM}" = "linux" ] && aprint_fail "${cb_red}not a linux console${c_res}, exiting." && exit 1
            [ -z "${1}" ] && aprint_fail "no ${cl_grn}vt${c_res} specified, exiting."     && exit 1

case "${1}" in
 *vt*) vt="$( echo "$1" | sed 's/vt//')";;
    *) vt="${1}"                        ;;
esac

case "${vt}" in
 [0-9])
  aprint "starting ${cl_grn}x${c_res}."
  startx -- vt${vt}
 ;;
  *)
  aprint_fail "${vt} is not a valid integerboi, exiting."
  exit 1
 ;;
esac
