#!/mss/bin/sh
. /mss/bin/apathy-funcs
if [ -z "$1" ]; then aprint_fail "no url given, exiting."; exit 1; fi
if [ "$2" = "novid" ]
 then extraflags="--no-video"
 else extraflags="--vo=gpu,drm"
fi

youtube-dl --list-format ${1} | grep "^[0-9]" > /tmp/ytquality.tmp

qlines=$(wc -l /tmp/ytquality.tmp)
quality=$(cat /tmp/ytquality.tmp | slmenu -b -l ${qlines} -p " * select stream quality:" | awk '{print $1}')

clear
aprint "playing ${c_lcyan}${1}${c_reset}."

mpv "${1}" --ytdl-format=${quality} "${extraflags}"
