#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

[ -z "${1}" ] \
 && aprint_fail "no ovpn specified, exiting." \
 && exit 1

ovpn_name=$(echo "${1}" | sed 's:.*/::')

aprint_nc
aprint_ret "getting auth."

 databoi="$(curl -s "https://freevpn.me/accounts" \
           | grep -o 'Password:<\/b> .\{0,12\}'   \
           | sed ' s/Password:<\/b>//g')"
evalretkill

aprint_ret "setting auth and user."
 case "${ovpn_name}" in
  *Server1*) passboi=$(echo $databoi | awk '{print $1}') ;;
  *Server2*) passboi=$(echo $databoi | awk '{print $2}') ;;
 esac
evalretkill

lsdetail "pass" "${passboi}"
lsdetail "ovpn" "${ovpn_name}"
aprint_nc

aprint_ret "setting pass in auth.txt."
 echo "freevpn.me" > /mnt/mss/stuff/techy-bits/openvpn/auth.txt
 echo "$passboi"   >> /mnt/mss/stuff/techy-bits/openvpn/auth.txt
evalretkill

aprint "connecting."
openvpn --config $1 > /tmp/vpn.log 2>&1 \
 || aprint_fail "failed, check /tmp/vpn.log."
