#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

if [ -z "$1" ]
then
 aprint_nc; aprint_fail "no ovpn config selected, exiting."
 aprint_nc; exit 1
fi

ovpn_name=$(printf "${1}\n" | sed 's:.*/::')

case "${ovpn_name}" in
 *FreeVPN.be*) _domain=be ;;
 *FreeVPN.co*) _domain=co ;;
 *FreeVPN.eu*) _domain=eu ;;
 *FreeVPN.im*) _domain=im ;;
 *FreeVPN.it*) _domain=it ;;
 *FreeVPN.me*) _domain=me ;;
 *FreeVPN.se*) _domain=se ;;
esac

aprint_nc
aprint_ret "getting auth details for ovpn from freevpn.${_domain}."
passboi=$(curl -s https://freevpn.${_domain}/accounts	\
 | grep -o 'Password.*'					\
 | awk -v FS="(Password:</b> |</li>)" '{print $2}')
evalretkill

aprint "pass\t\t\t: ${passboi}"
aprint_nc

aprint_ret "setting pass in auth.txt."
printf "freevpn.${_domain}\n" > /mnt/mss/stuff/techy-bits/openvpn/auth.txt &&
printf "${passboi}\n" >> /mnt/mss/stuff/techy-bits/openvpn/auth.txt
evalretkill

aprint "connecting to\t: ${ovpn_name}"
openvpn --config $1 > /tmp/vpn.log 2>&1 || \
 aprint_fail "failed, check /tmp/vpn.log."
