#!/bin/env bash
if [ "$(id -u)" -ne 0 ]; then printf "\n ! this script must be run as root, exiting.\n\n"; exit 1; fi

printf "\n ! this script will strip bins and libs which could be harmful.\n   are you sure you want to procceed? (y/n): "

read answer

if [ "$answer" != "${answer#[Yy]}" ]
then 
 printf "\n * stripping:\n"

 printf "  > /usr/lib\t\t(--strip-debug)"
 find /usr/lib		-type f -name \*.a -exec strip --strip-debug {} ';' > /dev/null 2>&1 &&
 printf "\t\t --> done.\n"

 printf "  > /lib\t\t(--strip-unneeded)"
 find /lib		-type f \( -name \*.so* -a ! -name \*dbg \) -exec strip --strip-unneeded {} ';' > /dev/null 2>&1 &&
 printf "\t --> done.\n"

 printf "  > /usr/lib\t\t(--strip-unneeded)"
 find /usr/lib		-type f \( -name \*.so* -a ! -name \*dbg \) -exec strip --strip-unneeded {} ';' > /dev/null 2>&1 &&
 printf "\t --> done.\n"

 printf "  > /bin\t\t(--strip-all)"
 find /bin		-type f -exec strip --strip-all {} ';' > /dev/null 2>&1	&&
 printf "\t\t --> done.\n"

 printf "  > /sbin\t\t(--strip-all)"
 find /sbin		-type f -exec strip --strip-all {} ';' > /dev/null 2>&1	&&
 printf "\t\t --> done.\n"

 printf "  > /usr/bin\t\t(--strip-all)"
 find /usr/bin		-type f -exec strip --strip-all {} ';' > /dev/null 2>&1	&&
 printf "\t\t --> done.\n"

 printf "  > /usr/sbin\t\t(--strip-all)"
 find /usr/sbin		-type f -exec strip --strip-all {} ';' > /dev/null 2>&1	&&
 printf "\t\t --> done.\n"

 printf "  > /usr/libexec\t(--strip-all)"
 find /usr/libexec	-type f -exec strip --strip-all {} ';' > /dev/null 2>&1	&&
 printf "\t\t --> done.\n"

 printf "\n * stripping complete.\n\n"

elif [ "$answer" != "${answer#[Nn]}" ];then exit 1
else echo " ! input y or n. "; exit 1
fi
