#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

if [ -z $1 ]; then printf "\n ! no option selected, exiting.\n\n"; exit 1; fi

case $1 in
 dnscrypt|-d)
  cp -v /etc/resolv.conf.dnscrypt /etc/resolv.conf	&&

  if [ -z "$(pidof dnscrypt-proxy)" ]
   then
    /etc/init.d/dnscrypt-proxy start > /dev/null 2>&1	&&
    printf "\n * dnscrypt service started.\n"
   else
    /etc/init.d/dnscrypt-proxy restart > /dev/null 2>&1	&&
    printf "\n * dnscrypt service restarted.\n"
  fi &&
  printf " * dns set to dnscrypt.\n\n"
 ;;
 flare|-f)
  cp -v /etc/resolv.conf.flare /etc/resolv.conf		&&

  if [ ! -z "$(pidof dnscrypt-proxy)" ]
   then /etc/init.d/dnscrypt-proxy stop			&&
   printf "\n * dnscrypt service stopped.\n"
  fi
  printf " * dns set to cloudflare.\n\n"
 ;;
 *)
  printf "\n ! option not recognized. options are:\n"	&&
  printf " * dnscrypt / -d\n * flare / -f\n\n"
esac
