#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

if [ -z $1 ]; then aprint_fail "no option specified in ${c_lcyan}\$1${c_reset}."; exit 1; fi

case $1 in
 dnscrypt|-d)
  aprint_nc

  aprint_ret "placing the dnscrypt resolv.conf."
  cp /etc/resolv.conf.dnscrypt /etc/resolv.conf
  evalretkill

  if [ -z "$(pidof dnscrypt-proxy)" ]
   then
    aprint_ret "starting dnscrypt."
    /etc/init.d/dnscrypt-proxy start > /dev/null 2>&1
    evalretkill
   else
    aprint_ret "restarting dnscrypt."
    /etc/init.d/dnscrypt-proxy restart > /dev/null 2>&1
    evalretkill
  fi
  aprint_nc
  aprint "dns resolver set to dnscrypt."
  aprint_nc
 ;;
 quad|-q)
  aprint_nc

  aprint_ret "placing the quad resolv.conf."
  cp /etc/resolv.conf.quad /etc/resolv.conf
  evalretkill

  if [ ! -z "$(pidof dnscrypt-proxy)" ]
   then
    aprint_ret "stopping dnscrypt."
    /etc/init.d/dnscrypt-proxy stop > /dev/null 2>&1
    evalretkill
  fi
  aprint_nc
  aprint "dns resolver set to quad."
  aprint_nc
 ;;
 *)
  aprint_fail "pick either: ${c_lcyan}quad|-q${c_reset} or ${c_lcyan}dnscrypt|-d${c_reset}"
esac
