#!/mss/bin/sh
dat=$(date "+%Y-%m-%d_%I-%M-%S%P_ttygrab")
loc="/home/mss/screenshots/tty/$dat.png"

grab_tty(){ fbcat > /tmp/tty.ppm ;}

if [ -z "$1" ]
 then grab_tty && convert /tmp/tty.ppm $loc && export savloc="$loc"
 else grab_tty && convert /tmp/tty.ppm $1 && export savloc="$1"
fi &&

printf " * tty grabbed to: ${savloc}.\n" &&
rm -rf /tmp/tty.ppm && printf " * removed the ppm.\n"
