pref("accessibility.force_disabled", 1);
pref("browser.aboutConfig.showWarning", false);
pref("browser.cache.disk.enable", true);
pref("browser.cache.memory.enable", false);
pref("browser.cache.offline.enable", true);
pref("browser.cache.offline.storage.enable", true);
pref("browser.download.hide_plugins_without_extensions", false);
pref("browser.download.manager.addToRecentDocs", false);
pref("browser.download.useDownloadDir", false);
pref("browser.preferences.defaultPerformanceSettings.enabled", false);
pref("browser.sessionstore.resume_from_crash", true);
pref("browser.shell.checkDefaultBrowser", false);
pref("browser.startup.homepage", "about:newtab");
pref("browser.startup.page", 0);
pref("browser.uidensity", 1);
pref("dom.allow_cut_copy", true);
pref("dom.event.clipboardevents.enabled", true);
pref("dom.ipc.processCount", 2);
pref("findbar.highlightAll", true);
pref("font.default.x-western", "sans-serif");
pref("font.name.monospace.ja", "xos4 Terminus");
pref("font.name.monospace.x-western", "xos4 Terminus");
pref("font.name.sans-serif.ja", "xos4 Terminus");
pref("font.name.sans-serif.x-western", "Liberation Sans");
pref("font.name.serif.ja", "xos4 Terminus");
pref("font.name.serif.x-western", "Liberation Sans");
pref("general.autoScroll", false);
pref("general.smoothScroll", false);
pref("general.warnOnAboutConfig", false);
pref("media.videocontrols.picture-in-picture.video-toggle.enabled", false);
pref("middlemouse.contentLoadURL", false);
pref("network.security.esni.enabled", true);
pref("network.trr.custom_uri", "https://127.0.0.1:3000/dns-query");
pref("network.trr.mode", 2);
pref("network.trr.uri", "https://127.0.0.1:3000/dns-query");
pref("reader.color_scheme", "dark");
pref("startup.homepage_override_url", "about:newtab");
pref("startup.homepage_welcome_url", "about:newtab");
pref("toolkit.cosmeticAnimations.enabled", false);
pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
pref("ui.systemUsesDarkTheme", true);
