#!/mss/bin/sh
. /mss/bin/apathy-init-funcs

# a1 >> set vars
sdir="/etc/apathy-init/scripts"

# a2 >> shut dmesg up for the love of god
dmesg --console-off

# a3 >> trap signals that may kill rc
trap "" INT QUIT TSTP

# b1 >> funcs
printlogo(){
 ainit_nc
 ainitmes "${c_red}   __,  ,_   __,  -/- /_";     ainit_nc
 ainitmes " (_/(__/_)_(_/(__/__/ (__(_/_";        ainit_nc
 ainitmes "      /                  _/_";         ainit_nc
 ainitmes "     /                  (/${c_reset}"; ainit_nc
 ainit_nc
}

welcome(){
 initver="$(/sbin/init --version | awk 'NR==1 {print tolower($1)$2,$4}')"
 curdate="$(date '+%a %d %I:%M:%S%P' | awk '{print tolower($1),$2,$3}')"
 curkern="$(uname -r)"

 clear; printlogo

 ainitmes "welcome to ${c_blue}apathy ${c_red}musl ${c_green}1.2${c_reset}."; ainit_nc
 ainitmes "running on kernel ${c_green}${curkern}${c_reset}.";                ainit_nc
 
 ainit_nc
 ainitmes "${c_green}${curdate}${c_reset} - ${c_green}${initver}${c_reset}";  ainit_nc
 ainit_nc
}

goodbye(){
 clear; printlogo

 ainitmes "shutting ${c_blue}apathy ${c_red}musl ${c_green}1.2${c_reset} down."; ainit_nc
 ainit_nc
}

case "${1}" in
 0)
  goodbye

  $sdir/gpm		stop
  $sdir/mpd		stop
  $sdir/dnscrypt-proxy	stop
  $sdir/ssh		stop
  $sdir/alsa		stop
  $sdir/random		stop
  $sdir/network		stop
  $sdir/sysklogd	stop
  $sdir/sendsignals	stop
  $sdir/swap		stop
  $sdir/mountfs		stop
  $sdir/localnet	stop

  halt -d -f -i -p
 ;;
 1)
  ainitmes "runlevel 1 is gay."
  warnprompt
 ;;
 2)
  ainitmes "runlevel 2 is gay."
  warnprompt
 ;;
 3)
  $sdir/sysklogd	start
  $sdir/iptables	start
  $sdir/network		start
  $sdir/random		start
  $sdir/gpm		start
  $sdir/mpd		start
  $sdir/dnscrypt-proxy	start
  $sdir/ssh		start
 ;;
 4)
  ainitmes "runlevel 4 is gay."
  warnprompt
 ;;
 5)
  ainitmes "runlevel 5 is gay."
  warnprompt
 ;;
 6)
  goodbye

  $sdir/gpm		stop
  $sdir/mpd		stop
  $sdir/dnscrypt-proxy	stop
  $sdir/ssh		stop
  $sdir/alsa		stop
  $sdir/random		stop
  $sdir/network		stop
  $sdir/sysklogd	stop
  $sdir/sendsignals	stop
  $sdir/swap		stop
  $sdir/mountfs		stop
  $sdir/localnet	stop

  reboot -d -f -i
 ;;
 S)
  welcome

  $sdir/mountvirtfs	start
  $sdir/localnet	start
  $sdir/udev		start
  $sdir/swap		start
  $sdir/checkfs		start
  $sdir/mountfs		start
  $sdir/setsched	start
  $sdir/cleanfs		start
  $sdir/alsa		start
  $sdir/console		start
 ;;
esac
