#!/mss/bin/sh
. /mss/initbits/bin/apathy-init-funcs

case "$1" in
 start)
  ainitmes "restoring ${c_lcyan}alsa volume states${c_reset}."
   alsactl restore >/dev/null 2>&1
  evalret
 ;;
 stop)
  ainitmes "saving ${c_lcyan}alsa volume states${c_reset}."
   alsactl store   >/dev/null 2>&1
  evalret
 ;;
 *)
  ainitusage "{start|stop}"
  exit 1
 ;;
esac
