#!/mss/bin/sh
. /mss/initbits/bin/apathy-init-funcs

case "${1}" in
 start)
  ainitmes "cleaning ${c_lcyan}/tmp${c_reset}."
   cd /tmp && find . -xdev -mindepth 1 ! -name lost+found -delete
  evalret

  ainitmes "utilizing ${c_lcyan}utmp${c_reset}."
   > /var/run/utmp && chmod 664 /var/run/utmp && chgrp utmp /var/run/utmp
  evalret
 ;;
 *)
  ainitusage "{start}"
  exit 1
 ;;
esac
