#!/mss/bin/sh
. /mss/initbits/bin/apathy-init-funcs

case "$1" in
 start)
  ainitmes "intializing the ${c_lcyan}kernel random number generator${c_reset}."
   [ -f /var/tmp/random-seed ] && cat /var/tmp/random-seed > /dev/urandom
   dd if=/dev/urandom of=/var/tmp/random-seed count=1 >/dev/null 2>&1
  evalret
 ;;
 stop)
  ainitmes "saving the ${c_lcyan}random seed${c_reset} to ${c_lcyan}/var/tmp${c_reset}."
   dd if=/dev/urandom of=/var/tmp/random-seed count=1 >/dev/null 2>&1
  evalret
 ;;
 *)
  ainitusage "{start|stop}"
  exit 1
 ;;
esac
