#!/mss/bin/sh
. /mss/bin/apathy-init-funcs

UNICODE="1"
KEYMAP="us"
FONT="ter-v12n -m 8859-1"

case "${1}" in
 start)
  ainitmes "setting up the ${c_lcyan}consolefont${c_reset}."
   setfont ${FONT}
  evalret

  ainitmes "figuring out the ${c_lcyan}mode command${c_reset}."
   MODE_COMMAND="printf '\033%G' && kbd_mode -u" || \
   MODE_COMMAND="printf '\033%@\033(K' && kbd_mode -a"
  evalret

  ainitmes "appyling the ${c_lcyan}mode command${c_reset} to all ${c_lcyan}terms${c_reset}."
   for TTY in $(grep 'respawn' /etc/inittab | awk '{gsub("--noclear",""); gsub("tty",""); print $2}')
    do openvt -f -w -c ${TTY} -- /bin/sh -c '${MODE_COMMAND}'; done
  evalret

  ainitmes "setting the ${c_lcyan}keymap${c_reset}."
   loadkeys ${KEYMAP} >/dev/null 2>&1
  evalret
 ;;
 *) ainitusage "{start}"
    exit 1
 ;;
esac
