#!/mss/bin/sh
. /mss/init/bin/funcs

case "$1" in
 start)
  ainitmes "${c_lcyan}(dnscrypt-proxy)${c_reset}: starting."
   cat > /etc/resolv.conf << "EOF"
nameserver 127.0.0.1
options edns0
EOF
   /opt/dnscrypt-proxy/dnscrypt-proxy &
  evalret
 ;;
 stop)
  ainitmes "${c_lcyan}(dnscrypt-proxy)${c_reset}: stopping."
   cat > /etc/resolv.conf << "EOF"
nameserver 1.1.1.1
nameserver 1.0.0.1
EOF
   ainit_kill dnscrypt-proxy
 ;;
 restart)
  ${0} stop; sleep 1; ${0} start
 ;;
 *)
  ainitusage "{start|stop|restart}"
  exit 1
 ;;
esac
