#!/mss/bin/sh
. /mss/init/bin/funcs

case "$1" in
 start)
  ainitmes "${c_lcyan}(dnscrypt-proxy)${c_reset}: starting."
   cp /etc/resolv.conf.dnscrypt /etc/resolv.conf
   /opt/dnscrypt-proxy/dnscrypt-proxy &
  evalret
 ;;
 stop)
  ainitmes "${c_lcyan}(dnscrypt-proxy)${c_reset}: stopping."
   case "$(tail -1 /etc/resolv.conf)" in
    *edns0*) cp /etc/resolv.conf.quad /etc/resolv.conf ;;
   esac
   kill -TERM $(pidof dnscrypt-proxy)
  evalret
 ;;
 restart)
  ${0} stop; sleep 1; ${0} start
 ;;
 *)
  ainitusage "{start|stop|restart}"
  exit 1
 ;;
esac
