#!/mss/bin/sh
. /mss/init/bin/funcs

case "$1" in
 start)
  ainitmes "${c_lcyan}(gpm)${c_reset}: starting."
   gpm -m /dev/input/mice -t imps2 >/dev/null 2>&1
  evalret
 ;;
 stop)
  ainitmes "${c_lcyan}(gpm)${c_reset}: stopping."
  ainit_kill gpm
 ;;
 restart)
  ${0} stop; sleep 1; ${0} start
 ;;
 *)
  ainitusage "{start|stop|restart}"
  exit 1
 ;;
esac
