#!/mss/bin/sh
. /mss/init/bin/funcs
rootcheck

case "$1" in
 start)
  ainitmes "${c_lcyan}(iptables)${c_reset}: starting."
   . /mss/init/config/iptables.conf
  evalret
 ;;
 lock)
  ainitmes "${c_lcyan}(iptables)${c_reset}: locking."
   iptables --policy INPUT   DROP     &&
   iptables --policy OUTPUT  DROP     &&
   iptables --policy FORWARD DROP     &&
   iptables --flush                   &&
   iptables -t mangle --flush         &&
   iptables --delete-chain            &&
   iptables -t mangle --delete-chain  &&
   iptables -A INPUT  -i lo -j ACCEPT &&
   iptables -A OUTPUT -o lo -j ACCEPT
  evalret
 ;;
 clear|stop)
  ainitmes "${c_lcyan}(iptables)${c_reset}: clearing."
   iptables --policy INPUT   ACCEPT
   iptables --policy OUTPUT  ACCEPT
   iptables --policy FORWARD ACCEPT
   iptables --flush
   iptables -t mangle --flush
   iptables --delete-chain
   iptables -t mangle --delete-chain
  evalret
 ;;
 status)
  iptables --numeric --list
  iptables -t mangle --numeric --list
 ;;
 *)
  ainitusage "{start|lock|clear|stop|status}"
  exit 1
 ;;
esac
