#!/mss/bin/sh
. /mss/init/bin/funcs

case "$1" in
 start)
  ainitmes "${c_lcyan}(mpd)${c_reset}: starting mpd."
   printf '' > /var/lib/mpd/log
   doas -u mpd /usr/bin/mpd /etc/mpd.conf >/dev/null 2>&1
  evalret

  ainitmes "${c_lcyan}(mpd)${c_reset}: setting up."
   mpc repeat  on  >/dev/null 2>&1 &&
   mpc random  off >/dev/null 2>&1 &&
   mpc single  off >/dev/null 2>&1 &&
   mpc consume off >/dev/null 2>&1
  evalret

  ainitmes "${c_lcyan}(mpd)${c_reset}: starting ympd."
   doas -u mpd ympd >/dev/null 2>&1 &
  evalret

  ainitmes "${c_lcyan}(mpd)${c_reset}: starting mpdas."
   doas -u mss mpdas >/dev/null 2>&1 &
  evalret
 ;;
 stop)
  ainitmes "${c_lcyan}(mpd)${c_reset}: stopping ympd."
  ainit_kill ympd

  ainitmes "${c_lcyan}(mpd)${c_reset}: stopping mpdas."
  ainit_kill mpdas

  ainitmes "${c_lcyan}(mpd)${c_reset}: stopping mpd."
  ainit_kill mpd
 ;;
 restart)
  ${0} stop; sleep 1; ${0} start
 ;;
 *)
  ainitusage "{start|stop|restart}"
  exit 1
 ;;
esac
