#!/mss/bin/sh
. /mss/init/bin/funcs
rootcheck

case "$1" in
 start)
  ainitmes "${c_lcyan}(mpd)${c_reset}: starting."
   echo > /var/lib/mpd/log
   doas -u mpd /usr/bin/mpd /etc/mpd.conf
   evalret
 ;;
 stop)
  ainitmes "${c_lcyan}(mpd)${c_reset}: stopping."
   kill -TERM $(cat /run/mpd.pid)
  evalret
 ;;
 restart)
  ${0} stop; sleep 1; ${0} start
 ;;
 *)
  ainitusage "{start|stop|restart}"
  exit 1
 ;;
esac
