#!/mss/bin/sh
. /mss/init/bin/funcs
rootcheck

 ip="192.168.1.31"
 pref="24"
 gway="192.168.1.1"
bcast="192.168.1.99"

case "${1}" in
 start)
  if [ -z "${2}" ]
   then ainitmes "specify iface as \$2."; failprompt; exit 1
   else iface="${2}"
  fi

  if ip addr | grep ${iface} | grep inet >/dev/null 2>&1; then
   ainitmes "ip already assigned to ${iface}, try disconnecting."; failprompt
   exit 1
  fi
 
  if [ "${iface}" = "wlan0" ]; then
   if [ -z "${3}" ]
    then ainitmes "specify wpaconf as \$3."; failprompt; exit 1
    else 
     wpaconf="/etc/wpa_supplicant/${3}.conf"
   
     if [ ! -f "${wpaconf}" ]; then
      aintimes "wpaconf not found.";failprompt; exit 1
     fi
  
     ainitmes "${c_lcyan}(network)${c_reset}: invoking wpa_supplicant."
      wpa_supplicant -B -i "${iface}" -c "${wpaconf}" >/dev/null 2>&1
     evalret
    fi
  fi
 
  ainitmes "${c_lcyan}(network)${c_reset}: adding ${ip} to ${iface}."
   ip addr add "${ip}/${pref}" broadcast "${bcast}" dev "${iface}"
  evalret
 
  ainitmes "${c_lcyan}(network)${c_reset}: bringing ${iface} up."
   ip link set ${iface} up
  evalret
 
  ainitmes "${c_lcyan}(network)${c_reset}: setting up the default gateway."
   ip route add default via ${gway} dev ${iface}
  evalret
 ;;
 stop)
  if [ -z "${2}" ]
   then ainitmes "specify iface as \$2."; failprompt; exit 1
   else iface="${2}"
  fi

  if ! ip addr | grep ${iface} | grep inet >/dev/null 2>&1; then
   ainitmes "no ip is assigned to ${iface}."; failprompt; exit 1
  fi
 
  if [ "${iface}" = "wlan0" ]; then
   kill -TERM $(pidof wpa_supplicant) >/dev/null 2>&1
  fi

  ainitmes "${c_lcyan}(network)${c_reset}: removing ${ip} from ${iface}."
   ip addr del "${ip}/${pref}" broadcast "${bcast}" dev "${iface}"
  evalret
 
  ainitmes "${c_lcyan}(network)${c_reset}: bringing ${iface} down."
   ip link set ${iface} down
  evalret
 ;;
 *)
  ainitusage "{start|stop}"
  exit 1
 ;;
esac
