#!/mss/bin/sh
. /mss/init/bin/funcs

case "$1" in
 start)
  case "${2}" in
   server)
    if [ ! -f /etc/exports ]
     then
      ainitmes "/etc/exports does not exist."; failprompt
      exit 1
    elif [ "$(cat /etc/exports | wc -l)" -eq 0 ]
     then
      ainitmes "/etc/exports is empty."; failprompt
      exit 1
    fi

    ainitmes "${c_lcyan}(nfs)${c_reset}: starting rpcbind."
     rpcbind
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: starting rpc.statd."
     rpc.statd --no-notify
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: starting rpc.nfsd."
     rpc.nfsd -p 2049 8
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: starting rpc.mountd."
     rpc.mountd
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: running exportfs."
     exportfs -ra >/dev/null 2>&1
    evalret
   ;;
   client)
    ainitmes "${c_lcyan}(nfs)${c_reset}: starting rpcbind."
     rpcbind
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: starting rpc.statd."
     rpc.statd --no-notify
    evalret
   ;;
   *)
    ainitmes "specify either client or server as \$2."; failprompt
    exit 1
   ;;
  esac
 ;;
 stop)
  case "${2}" in
   server)
    ainitmes "${c_lcyan}(nfs)${c_reset}: clearing exportfs."
     exportfs -au >/dev/null 2>&1
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: stopping rpcbind."
     kill -TERM $(pidof rpcbind)
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: stopping rpc.statd."
     kill -TERM $(pidof rpc.statd) &&
     if [ -f /var/run/rpc.statd.pid ]; then rm -f /var/run/rpc.statd.pid; fi
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: stopping kernel nfsd instances."
     nfsdpidlist="$(ps ax | grep '\[nfsd\]' | grep -v grep | awk '{print $1}')"
     for nfsdpid in $nfsdpidlist; do kill -HUP $nfsdpid; done
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: stopping rpc.mountd."
     kill -TERM $(pidof rpc.mountd)
    evalret
   ;;
   client)
    ainitmes "${c_lcyan}(nfs)${c_reset}: stopping rpcbind."
     kill -TERM $(pidof rpcbind)
    evalret
    ainitmes "${c_lcyan}(nfs)${c_reset}: stopping rpc.statd."
     kill -TERM $(pidof rpc.statd)
    evalret
   ;;
   *)
   ainitmes "specify either client or server as \$2."; failprompt
   exit 1
   ;;
  esac
 ;;
 reload)
  if [ "$(ps ax | grep '\[nfsd\]' | grep -v grep | wc -l)" -eq 0 ]
   then
    ainitmes "no nfsd kernel threads found."; failprompt
    exit 1
   else
    ainitmes "${c_lcyan}(nfs)${c_reset}: reloading exportfs."
     exportfs -ra >/dev/null 2>&1
    evalret
  fi
 ;;
 *)
  ainitusage "{start|stop|reload}"
  exit 1
 ;;
esac
