#!/mss/bin/sh
. /mss/init/bin/funcs

case "$1" in
 start)
  case "${2}" in
   server)
    if [ ! -f /etc/exports ]
     then
      ainitmes "/etc/exports does not exist."; failprompt
      exit 1
    elif [ "$(cat /etc/exports | wc -l)" -eq 0 ]
     then
      ainitmes "/etc/exports is empty."; failprompt
      exit 1
    fi

    ainitmes "${c_lcyan}(nfs)${c_reset}: starting rpcbind."
     rpcbind
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: starting rpc.statd."
     rpc.statd -p 31310 -o 31311 --no-notify
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: starting rpc.nfsd."
     rpc.nfsd -p 2049 8
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: starting rpc.mountd."
     rpc.mountd -p 31312
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: running exportfs."
     exportfs -ra >/dev/null 2>&1
    evalret
   ;;
   client)
    ainitmes "${c_lcyan}(nfs)${c_reset}: starting rpcbind."
     rpcbind
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: starting rpc.statd."
     rpc.statd -p 31310 -o 31311 --no-notify
    evalret
   ;;
   *)
    ainitmes "specify either client or server as \$2."; failprompt
    exit 1
   ;;
  esac
 ;;
 stop)
  case "${2}" in
   server)
    ainitmes "${c_lcyan}(nfs)${c_reset}: clearing exportfs."
     exportfs -au >/dev/null 2>&1
    evalret

    ainitmes "${c_lcyan}(nfs)${c_reset}: stopping rpcbind."
    ainit_kill rpcbind

    ainitmes "${c_lcyan}(nfs)${c_reset}: stopping rpc.statd."
    ainit_kill rpc.statd
    if [ -f /var/run/rpc.statd.pid ]; then rm -f /var/run/rpc.statd.pid; fi

    ainitmes "${c_lcyan}(nfs)${c_reset}: stopping kernel nfsd instances."
    ainit_kill nfsd

    ainitmes "${c_lcyan}(nfs)${c_reset}: stopping rpc.mountd."
    ainit_kill rpc.mountd
   ;;
   client)
    ainitmes "${c_lcyan}(nfs)${c_reset}: stopping rpcbind."
    ainit_kill rpcbind

    ainitmes "${c_lcyan}(nfs)${c_reset}: stopping rpc.statd."
    ainit_kill rpc.statd
    if [ -f /var/run/rpc.statd.pid ]; then rm -f /var/run/rpc.statd.pid; fi
   ;;
   *)
   ainitmes "specify either client or server as \$2."; failprompt
   exit 1
   ;;
  esac
 ;;
 reload)
  if [ -z "$(pgrep nfsd)" ]
   then
    ainitmes "no nfsd kernel threads found."; failprompt
    exit 1
   else
    ainitmes "${c_lcyan}(nfs)${c_reset}: reloading exportfs."
     exportfs -ra >/dev/null 2>&1
    evalret
  fi
 ;;
 *)
  ainitusage "{start|stop|reload}"
  exit 1
 ;;
esac
