#!/mss/bin/sh
. /mss/init/bin/funcs

case "$1" in
 start)
  ainitmes "${c_lcyan}(ssh)${c_reset}: starting."
   /usr/bin/sshd >/dev/null 2>&1
  evalret
 ;;
 stop)
  ainitmes "${c_lcyan}(ssh)${c_reset}: stopping."
  ainit_kill sshd
 ;;
 restart)
  ${0} stop; sleep 1; ${0} start
 ;;
 *)
  ainitusage "{start|stop|restart}"
  exit 1
 ;;
esac
