#!/mss/bin/sh
. /mss/init/bin/funcs

case "$1" in
 start)
  ainitmes "${c_lcyan}(thinkfan)${c_reset}: starting."
   thinkfan -s 5 -n -q >/dev/null 2>&1 &
  evalret
 ;;
 stop)
  ainitmes "${c_lcyan}(thinkfan)${c_reset}: stopping."
  ainit_kill thinkfan
 ;;
 restart)
  ${0} stop; sleep 1; ${0} start
 ;;
 *)
  ainitusage "{start|stop|restart}"
  exit 1
 ;;
esac
