#!/mss/bin/sh
. /mss/init/bin/funcs

case "$1" in
 start)
  ainitmes "${c_lcyan}(transmission)${c_reset}: starting."
   su mss -c \
    'transmission-daemon \
     --allowed "127.0.0.1,192.168.*.*" \
     --port    "9091"                  \
     --no-auth                         \
     --no-watch-dir                    \
     --no-incomplete-dir               \
     --dht                             \
     --utp                             \
     --paused                          \
     --portmap                         \
     --global-seedratio 0              \
     --pid-file "/run/transmission.pid"'
  evalret
 ;;
 stop)
  ainitmes "${c_lcyan}(transmission)${c_reset}: stopping."
   read transpid < /run/transmission.pid
   kill -TERM "$transpid"
  evalret
 ;;
 restart)
  ${0} stop; sleep 1; ${0} start
 ;;
 *)
  ainitusage "{start|stop|restart}"
  exit 1
 ;;
esac
