# /etc/bashrc
# aliases go here

# disable mc colors
alias mc="mc -b"

# shorten the fucking name of this thing
alias nc="ncmpcpp"

# colorerd ls and grep 
alias grep="grep --color=auto"

# ps1 thingy
export PS1="\[\e[34m\][\[\e[m\]\A\[\e[34m\]]\[\e[m\] \[\e[34m\]\u\[\e[m\] \[\e[36m\]\w\[\e[m\]: "
