" Begin /etc/vimrc

" Ensure defaults are set before customizing settings, not after
source $VIMRUNTIME/defaults.vim
let skip_defaults_vim=1 

set ruler
set nocompatible
set backspace=2
set mouse=
syntax on
colorscheme delek
if (&term == "xterm") || (&term == "putty")
  set background=dark
endif

" End /etc/vimrc
