// personal:
pref("accessibility.force_disabled", 1);
pref("browser.aboutConfig.showWarning", false);
pref("browser.cache.disk.enable", false);
pref("browser.cache.memory.enable", false);
pref("browser.cache.offline.enable", false);
pref("browser.cache.offline.storage.enable", false);
pref("browser.preferences.defaultPerformanceSettings.enabled", false);
pref("browser.sessionstore.resume_from_crash", true);
pref("browser.shell.checkDefaultBrowser", false);
pref("browser.startup.homepage", "about:newtab");
pref("browser.startup.page", 0);
pref("browser.uidensity", 1);
//	pref("devtools.onboarding.telemetry.logged", false);
pref("dom.allow_cut_copy", true);
pref("dom.event.clipboardevents.enabled", true);
pref("dom.ipc.processCount", 2);
pref("findbar.highlightAll", true);
pref("font.default.x-western", "sans-serif");
pref("font.name.monospace.ja", "xos4 Terminus");
pref("font.name.monospace.x-western", "xos4 Terminus");
pref("font.name.sans-serif.ja", "xos4 Terminus");
pref("font.name.sans-serif.x-western", "Liberation Sans");
pref("font.name.serif.ja", "xos4 Terminus");
pref("font.name.serif.x-western", "Liberation Sans");
pref("general.autoScroll", false);
pref("general.smoothScroll", false);
pref("general.warnOnAboutConfig", false);
//	pref("geo.enabled", false);
//	pref("geo.provider.use_gpsd", false);
//	pref("geo.wifi.scan", false);
//	pref("geo.wifi.uri", "");
pref("media.videocontrols.picture-in-picture.video-toggle.enabled", false);
pref("middlemouse.contentLoadURL", false);
//	pref("permissions.default.camera", 2);
//	pref("permissions.default.geo", 2);
//	pref("permissions.default.microphone", 2);
pref("reader.color_scheme", "dark");
pref("startup.homepage_override_url", "about:newtab");
pref("startup.homepage_welcome_url", "about:newtab");
pref("toolkit.cosmeticAnimations.enabled", false);
pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
pref("ui.systemUsesDarkTheme", true);
//	pref("webgl.disable-extensions", true);
//	pref("webgl.disable-fail-if-major-performance-caveat", true);
//	pref("webgl.disabled", true);
//	pref("webgl.dxgl.enabled", false);
//	pref("webgl.enable-webgl2", false);
//	pref("webgl.min_capability_mode", true);
