#!/mss/bin/sh
exec aria2c               \
 --disable-ipv6=true      \
 --max-tries=3            \
 --summary-interval=0     \
 --continue=true          \
 --always-resume=true     \
 --file-allocation=none   \
 --enable-rpc=true        \
 --rpc-listen-port=3131   \
 --rpc-secret=heh         \
 --rpc-listen-all=true    \
 --follow-torrent=false   \
 --seed-ratio=0           \
 --seed-time=0            \
 "${@}"
