#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

[ -z "$1" ] && aprint_fail "no mount point selected, exiting." && exit 1
[ -z "$2" ] && aprint_fail "no user selected, exiting."        && exit 1

aprint_nc
aprint_ret "mounting."
 mount --bind "$1" "$1"                    &&
 mount -t proc /proc "$1"/proc             &&
 mount --make-rslave --rbind /sys "$1"/sys &&
 mount --make-rslave --rbind /dev "$1"/dev &&
 mount --make-rslave --rbind /run "$1"/run
evalretkill

aprint "chrooting to ${cl_grn}$1${c_res} as user ${cl_grn}$2${c_res}."
aprint_nc
 chroot "$1"         \
  /usr/bin/env -i    \
   HOME=/home/mss    \
   TERM="$TERM"      \
   PS1='[chroot] : ' \
   DISPLAY=:0        \
   PATH=/bin:/usr/bin:/sbin:/usr/sbin \
    /bin/su - $2

aprint_nc
aprint_ret "exited chroot, unmounting."
 umount -l "$1"/proc &&
 umount -l "$1"/sys  &&
 umount -l "$1"/dev  &&
 umount -l "$1"/run  &&
 umount -l "$1" 
evalretkill

aprint_nc
