#!/mss/bin/sh
. /mss/bin/apathy-funcs
dat=$(date "+%Y%m%d_%H%M%S_maimcrop")
loc="/home/mss/screenshots/grabs/${dat}.png"

if [ -z "$1" ]
 then
  savloc="${loc}"
  maim -s -u > "${loc}"

  local error_value="${?}"
  if [ ! "${error_value}" = 0 ]; then
   rm -rfv "${savloc}"
   exit 1
  fi

 else
  savloc="$1"
  maim -s -u > "${1}"

  local error_value="${?}"
  if [ ! "${error_value}" = 0 ]; then
   rm -rfv "${savloc}"
   exit 1
  fi
fi

aprint_nc
aprint "grab saved to ${cb_grn}${savloc}${c_res}."
aprint_nc
