#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

case "${1}" in
 c)
  read govcurrent < /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
  aprint "current governor is ${cb_grn}${govcurrent}${c_res}."
  exit 0
 ;;
 *)
  read availgov < /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
   govlist="$(echo "${availgov}" | sed 's/ /\n/g')"
  govlines="$(echo "${govlist}"  | wc -l)"
  govapply="$(echo "${govlist}"  | slmenu -b -l "${govlines}" -p "pick the governor.")"

  aprint "setting the cpu governor to ${cb_grn}${govapply}${c_res}."

  for i in /sys/devices/system/cpu/*/cpufreq/scaling_governor; do
   echo "${govapply}" > "${i}"
  done
 ;;
esac
