#!/mss/bin/sh
. /mss/bin/apathy-funcs
rootcheck

if [ -z $1 ]; then aprint_fail "no option specified in ${cl_grn}\$1${c_res}."; exit 1; fi

case $1 in
 dnscrypt|-d)
  aprint_nc

  aprint_ret "placing the dnscrypt resolv.conf."
  cp /etc/resolv.conf.dnscrypt /etc/resolv.conf
  evalretkill

  if [ -z "$(pidof dnscrypt-proxy)" ]
   then
    aprint_ret "starting dnscrypt."
    /mss/initbits/scripts/dnscrypt-proxy start > /dev/null 2>&1
    evalretkill
   else
    aprint_ret "restarting dnscrypt."
    /mss/initbits/scripts//dnscrypt-proxy restart > /dev/null 2>&1
    evalretkill
  fi
  aprint_nc
  aprint "dns resolver set to dnscrypt."
  aprint_nc
 ;;
 cloudflare|-q)
  aprint_nc

  aprint_ret "placing the cloudflare resolv.conf."
  cp /etc/resolv.conf.cloudflare /etc/resolv.conf
  evalretkill

  if [ ! -z "$(pidof dnscrypt-proxy)" ]
   then
    aprint_ret "stopping dnscrypt."
    /mss/initbits/scripts/dnscrypt-proxy stop > /dev/null 2>&1
    evalretkill
  fi
  aprint_nc
  aprint "dns resolver set to cloudflare."
  aprint_nc
 ;;
 *)
  aprint_fail "pick either: ${cl_grn}cloudflare|-q${c_res} or ${cl_grn}dnscrypt|-d${c_res}"
esac
