#!/mss/bin/sh
. /mss/bin/apathy-funcs
dat=$(date "+%Y%m%d_%H%M%S_ttygrab")
loc="/home/mss/screenshots/tty/$dat.png"

grab_tty(){ fbcat > /tmp/tty.ppm ;}

if [ -z "$1" ]
 then
  savloc="${loc}"
  grab_tty
  convert /tmp/tty.ppm "${loc}"
 else
  savloc="$1"
  grab_tty
  convert /tmp/tty.ppm "${1}"
fi

rm -rf /tmp/tty.ppm

aprint_nc
aprint "tty grabbed to ${cb_grn}${savloc}${c_res}."
aprint_nc
