#!/mss/bin/sh
# a1 >> set vars
bitsdir="/mss/initbits"
sdir="${bitsdir}/scripts"

# a2 >> source the funcs
. "${bitsdir}"/bin/apathy-init-funcs

# a2 >> shut dmesg up for the love of god
dmesg --console-off

# a3 >> trap signals that may kill rc
trap "" INT QUIT TSTP

# b1 >> funcs
banner(){
 datefmt="$(date '+%a %d %I:%M:%S%P' | awk '{print tolower($0)}')"
 datefmt="${c_green}${datefmt}${c_reset}"

 clear

 ainit_nc; ainit_nc
 ainitmes "${c_blue}apathy ${c_red}musl ${c_lcyan}1.2 - ${datefmt}"; ainit_nc
 ainit_nc; ainit_nc
}

initboi(){
 banner

 ctrlaltdel -s

 $sdir/mountvirtfs	start || /bin/ash
 $sdir/localnet		start
 $sdir/udev		start
 $sdir/stdstreams	start

 $sdir/swap		start
 $sdir/checkfs		start
 $sdir/mountfs		start
 $sdir/setsched		start
 $sdir/cleanfs		start
 $sdir/alsa		start
 $sdir/console		start

 $sdir/sysklogd		start
 $sdir/iptables		start
 $sdir/network		start
 $sdir/random		start
 $sdir/gpm		start
 $sdir/mpd		start
 $sdir/dnscrypt-proxy	start
#$sdir/ssh		start

 /mss/bin/sh -c '/mss/initbits/bin/respawn \
                 /mss/initbits/bin/getty   \
                 /dev/tty1 linux' &>/dev/null &
 /mss/bin/sh -c '/mss/initbits/bin/respawn \
                 /mss/initbits/bin/getty   \
                 /dev/tty2 linux' &>/dev/null &
 /mss/bin/sh -c '/mss/initbits/bin/respawn \
                 /mss/initbits/bin/getty   \
                 /dev/tty3 linux' &>/dev/null &

 ainit_nc
}

poweroffboi(){
 banner

 stty onlcr

 $sdir/gpm		stop
 $sdir/mpd		stop
 $sdir/dnscrypt-proxy	stop
#$sdir/ssh		stop
 $sdir/alsa		stop
 $sdir/random		stop
 $sdir/network		stop
 $sdir/sysklogd		stop
 $sdir/sendsignals	stop
 $sdir/swap		stop
 $sdir/mountfs		stop
 $sdir/localnet		stop

 sync; sleep 3; halt -p
}

rebootboi(){
 banner

 $sdir/gpm		stop
 $sdir/mpd		stop
 $sdir/dnscrypt-proxy	stop
#$sdir/ssh		stop
 $sdir/alsa		stop
 $sdir/random		stop
 $sdir/network		stop
 $sdir/sysklogd		stop
 $sdir/sendsignals	stop
 $sdir/swap		stop
 $sdir/mountfs		stop
 $sdir/localnet		stop

 sync; sleep 3; halt -r
}

case "${1}" in
 init)      initboi     ;;
 reboot)    rebootboi   ;;
 poweroff)  poweroffboi ;;
 *)         ainitusage "{init|reboot|poweroff}"; exit 1 ;;
esac
