.Dd September 12, 2015
.Dt FALLOCATE 1
.Os ubase
.Sh NAME
.Nm fallocate
.Nd preallocate files
.Sh SYNOPSIS
.Nm
.Op Fl o Ar num
.Fl l Ar num
.Ar file ...
.Sh DESCRIPTION
.Nm
if necessary creates and preallocates each
.Ar file
without truncation.
.sp
Given the filesystem supports
.Xr fallocate 2 ,
it is a very fast method of preallocation.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl l Ar num
Preallocate
.Ar num
bytes.
.It Fl o Ar num
Offset allocation by
.Ar num
bytes.
.El
.Sh SEE ALSO
.Xr fallocate 2
