.Dd March 26, 2016
.Dt FSFREEZE 8
.Os ubase
.Sh NAME
.Nm fsfreeze
.Nd suspend access to a filesystem
.Sh SYNOPSIS
.Nm
.Po Fl f | Fl u Pc
.Ar mountpoint
.Sh DESCRIPTION
.Nm
suspends and resumes access to a filesystem.
.Nm
is intended to be used with hardware RAID devices that support the creation
of snapshots.
The
.Ar mountpoint
argument is the pathname of the directory where the filesystem is mounted.
The filesystem must be mounted to be frozen.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl f
Freeze the filesystem mounted at
.Ar mountpoint .
.It Fl u
Unfreeze the filesystem mounted at
.Ar mountpoint .
.El
.Sh SEE ALSO
.Xr mount 8
.Sh BUGS
Only works for ext3/4, reiserfs, jfs and xfs.
