.Dd February 2, 2015
.Dt GETTY 8
.Os ubase
.Sh NAME
.Nm getty
.Nd suckless linux getty
.Sh SYNOPSIS
.Nm
.Op Ar tty Op Ar term Op Ar cmd Op Ar args...
.Sh DESCRIPTION
.Nm
opens a tty device, prompts for a login name and by default
invokes the /bin/login program. You can start another program instead of
/bin/login via
.Ar cmd
with
.Ar args .
The hostname is printed in the login name prompt as well. The
.Ar tty
should be specified using an absolute path.
.Sh SEE ALSO
.Xr login 1