.Dd February 2, 2015
.Dt HWCLOCK 8
.Os ubase
.Sh NAME
.Nm hwclock
.Nd query or set the hardware clock
.Sh SYNOPSIS
.Nm
.Op Fl r | Fl s | Fl w
.Op Fl u
.Op Ar dev
.Sh DESCRIPTION
.Nm
is a tool for accessing the hardware clock. You can display the current time,
set the hardware clock from the System Time, or set the System Time from the
hardware clock. It currently only works with UTC. You can use
.Ar dev
to specify the RTC device node absolute path. By default
it will use
.Pa /dev/rtc .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl r
Read the hardware clock and print the time on stdout.
.It Fl s
Set the system time from the hardware clock.
.It Fl u
Use UTC. This is the default option.
.It Fl w
Set the hardware clock to the system time.
.El
