.Dd April 24, 2015
.Dt ID 1
.Os ubase
.Sh NAME
.Nm id
.Nd print real and effective user and group IDs
.Sh SYNOPSIS
.Nm
.Op Fl n
.Op Fl g | u | G
.Op Ar user | uid
.Sh DESCRIPTION
.Nm
prints user and group information of the calling process to standard output.
If a login name or uid is specified, the user and group information of that
user is displayed.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl n
Print names instead of ID numbers, for -g, -u, and -G.
.It Fl g
Print only the effective group ID.
.It Fl u
Print only the effective user ID.
.It Fl G
Display group information as whitespace separated numbers, in no particular order.
.El
.Sh SEE ALSO
.Xr who 1
