.Dd February 2, 2015
.Dt MESG 1
.Os ubase
.Sh NAME
.Nm mesg
.Nd display (do not display) messages from other users
.Sh SYNOPSIS
.Nm
.Op Fl n | Fl y
.Sh DESCRIPTION
.Nm
controls write access others have to the terminal device associated with
standard error output. If write access is allowed, then programs such as
.Xr talk 1
and
.Xr write 1
may display messages on the terminal.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl n
Disallow messages.
.It Fl y
Allow messages.
.El
.Sh SEE ALSO
.Xr talk 1 ,
.Xr write 1
