.Dd February 2, 2015
.Dt MKSWAP 8
.Os ubase
.Sh NAME
.Nm mkswap
.Nd set up a Linux swap area
.Sh SYNOPSIS
.Nm
.Ar device
.Sh DESCRIPTION
.Nm
sets up a Linux swap area on a device or in a file. The
.Ar device
argument will usually be a disk-partition but it can also be a file. After
creating the swap area you will typically need to use the
.Xr swapon 8
command to start using it.
.Sh SEE ALSO
.Xr swapon 8
