.Dd February 2, 2015
.Dt MOUNTPOINT 1
.Os ubase
.Sh NAME
.Nm mountpoint
.Nd check if a directory is a mountpoint
.Sh SYNOPSIS
.Nm
.Op Fl dq
.Ar directory
.Nm
.Fl x Ar device
.Sh DESCRIPTION
.Nm
checks if the
.Ar directory
is mentioned in the
.Pa /proc/mounts
file.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d
Print the major/minor device number of the filesystem on stdout.
.It Fl q
Be quiet, don't print anything.
.It Fl x
Print the major/minor device number of the
.Ar device
on stdout.
.El
.Sh SEE ALSO
.Xr mount 8
