.Dd March 26, 2016
.Dt NOLOGIN 8
.Os ubase
.Sh NAME
.Nm nologin
.Nd refuse login
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
prints a message informing the user that she
is not allowed to log in. If /etc/nologin.txt
exists, its content is printed instead of
the default message.
.Pp
.Nm
is intended to be specified as the user's
default shell.
.Sh EXIT STATUS
.Nm
returns a status code indicating failure.
