.Dd February 2, 2015
.Dt PIDOF 1
.Os ubase
.Sh NAME
.Nm pidof
.Nd find the process ID of a running program
.Sh SYNOPSIS
.Nm
.Op Fl o Ar pid1,pid2,...pidN
.Op Fl s
.Op Ar program...
.Sh DESCRIPTION
.Nm
finds the process id's of the named programs and prints them to
stdout.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl o
Tell pidof to omit processes with that process id. The special pid
%PPID can be used to name the parent process of the pidof program.
.It Fl s
Single shot - this instructs the program to only return one process id.
.El
.Sh SEE ALSO
.Xr killall5 8
