.Dd February 2, 2015
.Dt STAT 1
.Os ubase
.Sh NAME
.Nm stat
.Nd display file status
.Sh SYNOPSIS
.Nm
.Op Fl L
.Op Ar file...
.Sh DESCRIPTION
.Nm
displays information about the given
.Ar files
or stdin if no
.Ar files
are specified.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl L
Follow links.
.El
.Sh SEE ALSO
.Xr stat 2
