.Dd February 2, 2015
.Dt SWAPON 8
.Os ubase
.Sh NAME
.Nm swapon
.Nd enable devices and files for paging and swapping
.Sh SYNOPSIS
.Nm
.Op Fl dp
.Fl a | Ar device
.Sh DESCRIPTION
.Nm
is used to specify devices on which paging and swapping are to take place.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a
Make all devices marked as ``swap'' in
.Pa /etc/fstab
available, except for those with the ``noauto'' option.
.It Fl d
Discard freed swap pages before they are reused.
.It Fl p
Set higher priority than the default to the new swap area.
.El
