.Dd February 2, 2015
.Dt SWAPLABEL 8
.Os ubase
.Sh NAME
.Nm swaplabel
.Nd set the label of a swap filesystem
.Sh SYNOPSIS
.Nm
.Op Fl L Ar label
.Ar device
.Sh DESCRIPTION
.Nm
is used to change the label of a swap device or file.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl L Ar label
Change the label.
.El
