.Dd February 2, 2015
.Dt TRUNCATE 1
.Os ubase
.Sh NAME
.Nm truncate
.Nd shrink or extend the size of a file to the specified size
.Sh SYNOPSIS
.Nm
.Op Fl c
.Fl s Ar size
.Ar file...
.Sh DESCRIPTION
.Nm
shrinks or extends the size of each
.Ar file
specified size. A
.Ar file
argument that does not exist is created. If a
.Ar file
is larger than the specified
.Ar size ,
the extra data is lost. If a
.Ar file
is shorter, it is extended and the extended part (hole) reads as zero bytes.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c
Do not create any files.
.It Fl s Ar size
Set or adjust the file size by
.Ar size
bytes.
.El
.Sh SEE ALSO
.Xr ftruncate 2 ,
.Xr truncate 2