.Dd February 2, 2015
.Dt UPTIME 1
.Os ubase
.Sh NAME
.Nm uptime
.Nd tell how long the system has been running
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
gives a one line display of the following information. The current time, how
long the system has been running, how many users are currently logged on and
the system load averages for the past 1, 5 and 15 minutes.
.Sh SEE ALSO
.Xr ps 1 ,
.Xr utmp 5
