.Dd February 2, 2015
.Dt WATCH 1
.Os ubase
.Sh NAME
.Nm watch
.Nd execute a program periodically, showing output fullscreen
.Sh SYNOPSIS
.Nm
.Op Fl n Ar interval
.Op Fl t
.Ar command
.Sh DESCRIPTION
.Nm
runs
.Ar command
repeatedly, displaying its output one screenfull at a time. This allows you
to watch the program output change over time. By default the program is run
every 2 seconds and will run until terminated.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl n Ar interval
Specify the update interval.
.It Fl t
Turn off the header showing the interval, command and current time at the top
of the display, as well as the following blank line. This is the default
action.
.El
