#!/mss/bin/sh
# check if openvpn is running
if [ -z "$(pidof openvpn)" ]
 then memepn=off
 else memepn=on
fi

# set interface and old data path
bwadapter=$(ip route | awk '/^default/ {print $5}')
bwpath="/tmp/bw.tmp"

# read rx-tx rates, save current time
read rx < "/sys/class/net/${bwadapter}/statistics/rx_bytes"
read tx < "/sys/class/net/${bwadapter}/statistics/tx_bytes"
time=$(date +%s)

# create if old data path doesn't exist
if [ ! -f "${bwpath}" ]
 then
  echo "${time} ${rx} ${tx}" > "${bwpath}"
  chmod 0666 "${bwpath}"
fi

# save old data, print new
read old < "${bwpath}"
echo "${time} ${rx} ${tx}" > "${bwpath}"

# get time diff for division and sanity
time_diff=$(( $time - $(echo $old | awk '{print $1}') ))

# sanity check, die if time diff is 0
if [ ! "${time_diff}" -gt 0 ]; then exit 1; fi

# get bw diff
rx_diff=$(( $rx - $(echo $old | awk '{print $2}') ))
tx_diff=$(( $tx - $(echo $old | awk '{print $3}') ))
rx_rate=$(( $rx_diff / $time_diff ))
tx_rate=$(( $tx_diff / $time_diff ))

# get total bw usage for session
total_rx=$(echo "$(($rx / 1048576))")
total_tx=$(echo "$(($tx / 1048576))")

# get current speed
rx_kib=$(echo "$(($rx_rate / 1024))")
tx_kib=$(echo "$(($tx_rate / 1024))")

# print sum
printf "${rx_kib}(${total_rx})rx ${tx_kib}(${total_tx})tx ${memepn}\n"
