#!/usr/bin/env bash
capstat=$(amixer -D default get Capture | tail -1 | sed 's/\[//g;s/\]//g')
cmchk=$(echo $capstat | awk '{print $7}')

if [ "$cmchk" = "off" ]
 then echo muted
 else echo $capstat | awk '{print $6}'
fi

case $BLOCK_BUTTON in
 3) amixer -q -D default set Capture toggle && pkill -RTMIN+1 i3blocks;;
 4) amixer -q -D default set Capture 3dB+ unmute && pkill -RTMIN+1 i3blocks;;
 5) amixer -q -D default set Capture 3dB- unmute && pkill -RTMIN+1 i3blocks;;
esac
