#!/mss/bin/sh
dat=$(date "+%Y-%m-%d_%I-%M-%S%P_maimcrop")
loc="/home/mss/screenshots/grabs/$dat.png"

if [ -z "$1" ]
 then
  export savloc="$loc"
  maim -s -u > $loc || rm -rfv $savloc && exit 1
 else
  export savloc="$1"
  maim -s -u > $1 || rm -rfv $savloc && exit 1
fi &&

printf " * screen grabbed to: ${savloc}.\n"
