#!/mss/bin/sh
# check if mpd is running
if [ $(pidof mpd) ]
 then mpd_running=1
 else mpd_running=0
fi

# if running, check if idle
if [ "${mpd_running}" = "1" ]
 then	 
  mpc_status="$(mpc status)"

  case "$(echo "${mpc_status}" | head -1)" in
   *volume:*)   mdp_idle=1	;;
   *)           mpd_idle=0	;;
  esac

  # if not idle, continue
  if [ "${mpd_idle}" = "0" ]
   then
    # a >> export current mpd state
    mpc_current="$(mpc current)"
  
    # b >> check if song is labeled or not
    # then print the song and artist name
    case "${mpc_current}" in
     *unorganized/*)
      song="$(echo ${mpc_current} | sed 's/unorganized\///;s/.mp3//;s/.flac//;s/.wav//' \
       | awk -v len=35 '{ if (length($0) > len) print substr($0, 1, len-3) "..."; else print; }')"
      ;;
     *)
      artist="$(echo "${mpc_current}" | cut -f1 -d"-" \
       | awk -v len=20 '{ if (length($0) > len) print substr($0, 1, len-3) "..."; else print; }')"
      art="$(echo "${mpc_current}" | sed 's/^.*- //' \
       | awk -v len=25 '{ if (length($0) > len) print substr($0, 1, len-3) "..."; else print; }')"
      song="$(echo "${artist}- ${art}")"
      ;;
    esac
  
    # c >> get duration
    main="$(echo "${mpc_status}" | head -2 | tail -1 | awk '{print $3}' | sed 's/\// /g;s/:/ /g')"
  
    curr_mins="$(echo "${main}" | awk '{print $1}')"
    curr_secs="$(echo "${main}" | awk '{print $2}')"
    curr=$(echo "$curr_secs + ($curr_mins * 60)" | bc -l)
  
    total_mins="$(echo "${main}" | awk '{print $3}')"
    total_secs="$(echo "${main}" | awk '{print $4}')"
    total=$(echo "$total_secs + ($total_mins * 60)" | bc -l)
  
    dur_pre="$(echo $(($total - $curr)))"
  
    # d >> check if longer than 3599 secs
    if [ "$dur_pre" -gt "3599" ]
     then dur="$(printf '%02d:%02d:%02d\n' $(($dur_pre/3600)) $(($dur_pre%3600/60)) $(($dur_pre%60)))"
     else dur="$(printf '%02d:%02d\n' $(($dur_pre%3600/60)) $(($dur_pre%60)))"
    fi
    
    # e >> get play/pause state and export final state
    plpa="$(echo "${mpc_status}" | tail -2 | head -1 | awk '{print $1}')"
  
    if [ "${plpa}" = "[paused]" ]
     then state="[paused] ${song}"
     else state="${song} ${dur}"
    fi
  
   else
    state="mpd is idle"
  fi
 
 else
  state="mpd is not running"
fi
echo "${state}"

# i3blocks interaction
case $BLOCK_BUTTON in
 1) mpc next		;;
 2) mpc toggle		;;
 3) mpc prev		;;
 4) mpc volume +10	;;
 5) mpc volume -10	;;
esac
