#!/bin/dash

getkern=$(uname -r | cut -c-4 | sed 's/\.//g')

if [ "$getkern" -le "49" ]
 then ptemp=$(sensors | grep 'Physical id 0:' | sed 's/Physical id 0:  +//g;s/°C  (high = +80.0°C, crit = +100.0°C)//g')
 else ptemp=$(sensors | grep 'Package id 0:' | sed 's/Package id 0:  +//g;s/°C  (high = +80.0°C, crit = +100.0°C)//g')
fi

echo "${ptemp}c"
