#!/mss/bin/sh
. /mss/bin/apathy-init-funcs

case "$1" in
 start)
  ainitmes "setting the clock ${c_lcyan}(hardware to system)${c_reset}."
   hwclock --hctosys --utc >/dev/null
  evalret
 ;;
 stop)
  ainitmes "setting the clock ${c_lcyan}(system to hardware)${c_reset}"
   hwclock --systohc >/dev/null
  evalret
 ;;
 *)
  ainitusage "{start|stop}"
  exit 1
 ;;
esac
