#!/mss/bin/sh
cap_data=$(amixer -D default get Capture | awk 'NR==6 {gsub("\\[",""); gsub("\\]",""); print}')

[ "$(echo $cap_data | awk '{print $7}')" = "off" ]        \
 && alsa_capture="muted"                                  \
 || alsa_capture="$(echo ${cap_data} | awk '{print $6}')"

echo "${alsa_capture}"

case $BLOCK_BUTTON in
 3) amixer set Capture toggle;      pkill -RTMIN+1 i3blocks;;
 4) amixer set Capture 3dB+ unmute; pkill -RTMIN+1 i3blocks;;
 5) amixer set Capture 3dB- unmute; pkill -RTMIN+1 i3blocks;;
esac
