#!/mss/bin/sh
mas_data=$(amixer -D default get Master | awk 'NR==5 {gsub("\\[",""); gsub("\\]",""); print}')
mmchk=$(echo $mas_data | awk '{print $6}')

[ "$mmchk" = "off" ] \
 && echo "muted"     \
 || echo "$(echo ${mas_data} | awk '{print $4}')"

case $BLOCK_BUTTON in
 3) amixer -q -D default sset Master toggle;      pkill -RTMIN+1 i3blocks;;
 4) amixer -q -D default sset Master 3dB+ unmute; pkill -RTMIN+1 i3blocks;;
 5) amixer -q -D default sset Master 3dB- unmute; pkill -RTMIN+1 i3blocks;;
esac
