#!/mss/bin/sh
speak_data=$(amixer -D default get Speaker | awk 'NR==6 {gsub("\\[",""); gsub("\\]",""); print}')

[ "$(echo $speak_data | awk '{print $7}')" = "off" ]      \
 && alsa_speak="muted"                                    \
 || alsa_speak="$(echo ${speak_data} | awk '{print $5}')"

echo "${alsa_speak}"

case $BLOCK_BUTTON in
 3) amixer -q -D default set Speaker toggle;      pkill -RTMIN+1 i3blocks;;
 4) amixer -q -D default set Speaker 3dB+ unmute; pkill -RTMIN+1 i3blocks;;
 5) amixer -q -D default set Speaker 3dB- unmute; pkill -RTMIN+1 i3blocks;;
esac
