#!/mss/bin/sh
cap_data=$(amixer -D default get Capture | awk 'NR==6 {gsub("\\[",""); gsub("\\]",""); print}')
cmchk=$(echo $cap_data | awk '{print $7}')

[ "$cmchk" = "off" ] \
 && echo "muted"     \
 || echo "$(echo ${cap_data} | awk '{print $6}')"

case $BLOCK_BUTTON in
 3) amixer -q -D default set Capture toggle;      pkill -RTMIN+1 i3blocks;;
 4) amixer -q -D default set Capture 3dB+ unmute; pkill -RTMIN+1 i3blocks;;
 5) amixer -q -D default set Capture 3dB- unmute; pkill -RTMIN+1 i3blocks;;
esac
