#!/mss/bin/sh
bwadapter="eth0"
[ -z "$(pidof openvpn)" ] && memepn=off || memepn=on

read rx1 < "/sys/class/net/${bwadapter}/statistics/rx_bytes"
read tx1 < "/sys/class/net/${bwadapter}/statistics/tx_bytes"
 sleep 1
read rx2 < "/sys/class/net/${bwadapter}/statistics/rx_bytes"
read tx2 < "/sys/class/net/${bwadapter}/statistics/tx_bytes"

rx_kib=$((($rx2 - $rx1) / 1024))
tx_kib=$((($tx2 - $tx2) / 1024))

total_rx=$(($rx2 / 1048576))
total_tx=$(($tx2 / 1048576))

printf "${rx_kib}(${total_rx})rx ${tx_kib}(${total_tx})tx ${memepn}\n"
