#!/mss/bin/sh
#bwadapter="eth0"
bwadapter="wlan0"

while :; do
 [ -z "$(pidof openvpn)" ] && memepn=off || memepn=on
 
 read rx1 < "/sys/class/net/${bwadapter}/statistics/rx_bytes"
 read tx1 < "/sys/class/net/${bwadapter}/statistics/tx_bytes"
  sleep 1
 read rx2 < "/sys/class/net/${bwadapter}/statistics/rx_bytes"
 read tx2 < "/sys/class/net/${bwadapter}/statistics/tx_bytes"
 
 rx_kib=$(echo "(${rx2} - ${rx1}) / 1024" | bc)
 tx_kib=$(echo "(${tx2} - ${tx1}) / 1024" | bc)
 
 total_rx=$(echo "$rx2 / 1048576" | bc)
 total_tx=$(echo "$tx2 / 1048576" | bc)
 
 echo " ${rx_kib}(${total_rx})rx ${tx_kib}(${total_tx})tx ${memepn}"
done
