#!/mss/bin/sh
s1_data=$(grep cpu /proc/stat | head -1)
s1_total=$(($(echo $s1_data | awk '{gsub(" ","+"); gsub("cpu","0"); print}')))
s1_col4=$(echo $s1_data | awk '{print $5}')

sleep 1

s2_data=$(grep cpu /proc/stat | head -1)
s2_total=$(($(echo $s2_data | awk '{gsub(" ","+"); gsub("cpu","0"); print}')))
s2_col4=$(echo $s2_data | awk '{print $5}')

used=$(((${s2_total} - ${s1_total}) - (${s2_col4} - ${s1_col4})))
thrd=$(awk '{print $4}' /proc/loadavg)
load=$((100 * ${used} / (${s2_total} - ${s1_total})))

temp0=$(cut -b1-2 /sys/class/hwmon/hwmon2/temp2_input)
temp1=$(cut -b1-2 /sys/class/hwmon/hwmon2/temp3_input)

echo "${load}% ${thrd} ${temp0}/${temp1}c"
