#!/mss/bin/sh
sel=$(printf "apathy-browser\nkill-cwm\nreboot\npoweroff" | dmenu -b -p "meh:")

case "$sel" in
 poweroff)
  kill -KILL $(pidof apathy-browser)
  doas -- init 0
 ;;
 reboot)
  kill -KILL $(pidof apathy-browser)
  doas -- init 6
 ;;
 kill-cwm)
  kill -KILL $(pidof apathy-browser)
  kill -KILL -$(cat /tmp/lemonbar.pid)
  kill -TERM $(pidof cwm)
 ;;
 apathy-browser)
  apathy-browser
 ;;
esac
