#!/mss/bin/sh
sel=$(printf "apathy-browser\nkill-i3\nreboot\npoweroff" | dmenu -b -p "meh:")

case "$sel" in
 poweroff)
  kill -KILL $(pidof apathy-browser)
  doas -- init 0
 ;;
 reboot)
  kill -KILL $(pidof apathy-browser)
  doas -- init 6
 ;;
 kill-i3)
  kill -KILL $(pidof apathy-browser)
  kill -TERM $(pidof i3)
 ;;
 apathy-browser)
  apathy-browser
 ;;
esac
