#!/mss/bin/sh
cur_zero="\\033[0G"
spaceboi=" "

spinnyboi(){
 printf "${cur_zero}${spaceboi}-";  sleep 0.1
 printf "${cur_zero}${spaceboi}\\"; sleep 0.1
 printf "${cur_zero}${spaceboi}|";  sleep 0.1
 printf "${cur_zero}${spaceboi}/";  sleep 0.1
}

while :; do spinnyboi; done || printf "\n"

