#!/mss/bin/sh
while :; do
 printf "%s | %srpm | p:%sc c:%s/%sc\n" \
 "$(date '+%H:%M:%S')"                    \
 "$(cat /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon*/fan1_input)"    \
 "$(cut -b1-2 /sys/devices/platform/coretemp.0/hwmon/hwmon*/temp2_input)" \
 "$(cut -b1-2 /sys/devices/platform/coretemp.0/hwmon/hwmon*/temp2_input)" \
 "$(cut -b1-2 /sys/devices/platform/coretemp.0/hwmon/hwmon*/temp3_input)"

 sleep 2
done
