#!/mss/bin/sh
cur_zero="\\033[0G"
i=0

printf "\n"
while :; do
 pr=$(printf "%02d:%02d:%02.0f" \
             "$(((${i}%86400)/3600))" \
             "$(((${i}%3600)/60))"    \
             "$((${i}%60))")

 printf "${cur_zero}   ${pr}"
 i=$((${i}+1))
 sleep 1
done
