#!/mss/bin/sh
upt=$(awk '{print int($1)}' /proc/uptime)

if   [ "${upt}" -lt 3600  ]; then printf "%02d:%02.0f\n"            \
                                         "$(((${upt}%3600)/60))"    \
                                         "$((${upt}%60))"
elif [ "${upt}" -lt 86400 ]; then printf "%02d:%02d:%02.0f\n"       \
                                         "$(((${upt}%86400)/3600))" \
                                         "$(((${upt}%3600)/60))"    \
                                         "$((${upt}%60))"
else                              printf "%d:%02d:%02d:%02.0f\n"    \
                                         "$((${upt}/86400))"        \
                                         "$(((${upt}%86400)/3600))" \
                                         "$(((${upt}%3600)/60))"    \
                                         "$((${upt}%6))"
fi
