#!/bin/env bash
while test $# -gt 0; do
 case "$1" in
  -h|--help)
   echo "chroot and run programs while allowing x access." && echo
   echo "specify executable by	-e or --exec."
   echo "specify chroot dir by	-p or --part."
   echo "specify user by		-u or --user."
   exit 0
   ;;
  -e|--exec)	shift; export chprog=$1;		shift;;
  -p|--part)     shift; export chpart=$1;  		shift;;
  -u|--user)    shift; export chuser=$1;		shift;;
  *)		echo "$1 is not a recognized flag!";    break;;
 esac
done


if [ "$(id -u)" -ne 0 ]
 then echo -e " ! this script must be run by root.";	exit 1
elif [ -z "$chprog" ]
 then echo -e " ! no program specified.";		exit 1
elif [ -z "$chpart" ]
 then echo -e " ! no partition specified.";		exit 1
elif [ -z "$chuser" ]
 then echo -e " ! no user specified.";			exit 1
fi

echo -e "\n * executing \"$chprog\" in \"$chpart\" as \"$chuser\"\n"

echo " * allowing all connections to X." && xhost + > /dev/null 2>&1 &&
echo " * mounting." &&
 mount --bind $chpart $chpart &&
 mount -t proc /proc $chpart/proc &&
 mount --make-rslave --rbind /sys $chpart/sys &&
 mount --make-rslave --rbind /dev $chpart/dev &&
 mount --make-rslave --rbind /run $chpart/run &&
echo " * mounted, chrooting." && chroot "${chpart}" su -c "${chprog}" "${chuser}" > /dev/null 2>&1

echo " * exited chroot, umounting." &&
 umount -l $chpart/{proc,sys,dev,run} &&
 umount -l $chpart &&
echo " * umounted successfully." &&
echo " * reverting xhost perms." && xhost - > /dev/null 2>&1 && echo " * done."
