#!/bin/sh
FIFO="/tmp/dvtm-status.$$"

[ -p "$FIFO" ] || mkfifo -m 600 "$FIFO" || exit 1

while true; do
 bw=$(/home/mss/.config/scripts/bw)
 cpu=$(/home/mss/.config/scripts/cpu)
 ptemp=$(/home/mss/.config/scripts/ptemp)
 mem=$(/home/mss/.config/scripts/mem)
 mpdstat=$(/home/mss/.config/scripts/mpdstat)
 time=$(date '+%a %d %I:%M:%S%P')
 #weather-local=$(/home/mss/.config/scripts/tmux-weather)
 host=$(cat /etc/hostname)
 uptime=$(/home/mss/.config/scripts/uptime)

 echo "${bw} | ${cpu} ${pthemp} ${mem} | ${mpdstat} | ${time} ${weather-local} | ${host} ${uptime}" 
done > "$FIFO" &

STATUS_PID=$!
dvtm -s "$FIFO" "$@" 2> /dev/null
kill $STATUS_PID
wait $STATUS_PID 2> /dev/null
rm -f "$FIFO"
