#!/bin/env bash
if [ -z $1 ]; then echo " ! no bg image selected."; exit 1; fi 

echo -ne "\e[?25l"

fbv -ciuker "$1" << EOF
q
EOF

shift

export FBTERM_BACKGROUND_IMAGE=1
export yes_fbterm=1
exec fbterm "$@"
