#!/bin/dash
printf "  _______ _______ _______
 |   |   |     __|     __|
 |       |__     |__     |
 |__|_|__|_______|_______|\n"

dist=$(grep "ID" "/etc/lsb-release" | sed 's/DISTRIB_ID\=//g;s/\"//g')
host=$(cat /etc/hostname)
cpu=$(lscpu | grep "Model name" | sed -r 's/Model name://g;s/^ *//g;s/CPU //g;s/\s+\S+$//;s/\s+\S+$//' | cut -d' ' -f2-)
freq_old=$(lscpu | grep "CPU MHz:" | sed 's/CPU MHz://g;s/[.].*$//;s/[[:blank:]]//g')
freq=$(printf "${freq_old} / 1000\n" | bc -l | cut -c-5)
kern=$(uname -r)
upt=$(uptime --pretty | sed 's/up //;s/\ days\?,/d/;s/\ hours\?,\?/h/;s/\ minutes\?/m/')
mem=$(free -h | sed -n '2p' | awk '{print $3"/"$2}')

printf "\n * host\t: ${host}\n * dist\t: ${dist}\n * kern\t: ${kern}\n * sh\t: $SHELL\n * upt\t: ${upt}\n * cpu\t: ${cpu} @ ${freq}GHz\n * mem\t: ${mem}\n\n"
