#!/bin/env bash
logloc="/var/log/sleeptrack"

date_wc=$(date '+%a %d/%m/%Y')
date_full=$(date '+%d/%m/%Y %I:%M:%S%P')
date_epoch=$(date +%s)

slept (){
 echo -e "[$date_wc]\nstart	$date_epoch	($date_full)" >> $logloc/sleep.log
}

woke (){
 echo "stop	$date_epoch	($date_full)" >> $logloc/sleep.log &&
 cat $logloc/sleep.log | tail -2 | awk '{print $2}' > $logloc/lastsleep.log

 wenttobed=$(cat $logloc/lastsleep.log | head -1 | xargs echo)
 wokeup=$(cat $logloc/lastsleep.log | tail -1 | xargs echo)

 sleeptime=$(echo "$wokeup - $wenttobed" | bc -l) 
 sleeptime_mins=$(echo $sleeptime / 60 | bc -l | cut -c-5)

 echo -e "total	$sleeptime_mins minutes ($sleeptime seconds)\n" >> $logloc/sleep.log
}

display_last (){
 cat $logloc/sleep.log | tail -5
}

while test $# -gt 0; do
 case "$1" in
  -h|--help)
   shift
   echo	"-s/slept	mark current time as the beginning of sleep."
   echo	"-w/woke	mark current time as the end of sleep."
   echo	"-d/display	display the results for the last sleep."
   shift
   ;;
  -s|slept)	shift; slept;				shift;;
  -w|woke)	shift; woke;				shift;;
  -d|display)	shift; display_last			shift;;
  *)		echo "$1 is not a recognized flag!";	break;;
 esac
done
