#!/bin/env bash
if [ "$(id -u)" -ne 0 ]; then
 echo -e " ! this script must be run by root."
exit 1
fi

cp -iv arch/x86/boot/bzImage	/boot/vmlinuz		&&
cp -iv System.map		/boot/System.map	&&
cp -iv .config			/boot/config		&&
