#!/bin/env bash
if [ "$(id -u)" -ne 0 ]; then
 echo -e " ! this script must be run by root."
exit 1
fi

mntp="/mnt/mss/stuff/chr"

echo " * allowing all connections to X." && xhost + &&
echo " * mounting." &&
 mount --bind $mntp $mntp &&
 mount -t proc /proc $mntp/proc &&
 mount --make-rslave --rbind /sys $mntp/sys &&
 mount --make-rslave --rbind /dev $mntp/dev &&
 mount --make-rslave --rbind /run $mntp/run &&
echo " * mounted, chrooting." && chroot $mntp /bin/bash
echo " * exited chroot, umounting." &&
 umount -l $mntp/{proc,sys,dev,run} &&
 umount -l $mntp &&
echo " * umounted successfully." &&
echo " * reverting xhost perms." && xhost - && echo " * done."
