#!/bin/env bash
if [ -z "$1" ]
 then echo " ! no ovpn config selected."
 exit 1;
fi

echo " * getting pass."						&&
passboi=$(curl -s https://freevpn.me/accounts	\
 | grep -o 'Password.*'				\
 | awk -v FS="(Password:</b> |</li>)" '{print $2}')		&&

echo " * setting pass."						&&
echo "freevpn.me" > /mnt/mss/stuff/techy-bits/openvpn/auth.txt	&&
echo "${passboi}" >> /mnt/mss/stuff/techy-bits/openvpn/auth.txt	&&

echo " * pass set, auth.txt:"					&&
cat /mnt/mss/stuff/techy-bits/openvpn/auth.txt			&&

echo " * connecting to $1"					&&
doas -- openvpn --config $1
