#!/bin/dash
if [ -z "$1" ]; then printf "\n ! no ovpn config selected, exiting.\n\n"; exit 1; fi

printf " * getting pass."						&&
passboi=$(curl -s https://freevpn.me/accounts	\
 | grep -o 'Password.*'				\
 | awk -v FS="(Password:</b> |</li>)" '{print $2}')			&&

printf " * setting pass.\n"						&&
printf "freevpn.me\n" > /mnt/mss/stuff/techy-bits/openvpn/auth.txt	&&
printf "${passboi}\n" >> /mnt/mss/stuff/techy-bits/openvpn/auth.txt	&&

printf " * pass set, auth.txt:\n"					&&
cat /mnt/mss/stuff/techy-bits/openvpn/auth.txt				&&

printf " * connecting to $1\n"						&&
doas -- openvpn --config $1
