#!/usr/bin/env perl
use Time::HiRes qw(usleep);
use Env qw(BLOCK_INSTANCE);

use constant DELAY => 50; # Delay in ms to let network-based players (spotify) reflect new data.

my @metadata = ();
my $player_arg = "";

if ($BLOCK_INSTANCE) {
    $player_arg = "--player='$BLOCK_INSTANCE'";
}

sub buttons {
    my $method = shift;

    if($method eq 'mpd') {
        if ($ENV{'BLOCK_BUTTON'} == 1) {
            system("mpc prev");
        } elsif ($ENV{'BLOCK_BUTTON'} == 2) {
            system("mpc toggle");
        } elsif ($ENV{'BLOCK_BUTTON'} == 3) {
            system("mpc next");
	} elsif ($ENV{'BLOCK_BUTTON'} == 4) {
            system("mpc volume +10");
	} elsif ($ENV{'BLOCK_BUTTON'} == 5) {
            system("mpc volume -10");
	}

   
    }
}

sub mpd {
    my $data = qx(mpc current);
    if (not $data eq '') {
        buttons("mpd");
        print($data);
        exit 0;
    }
}



if ($player_arg eq '' or $player_arg =~ /mpd/) {
    mpd;
}
print("\n");
