#!/bin/env bash
# mount garbage
mount	--rbind		/dev	/mnt/dev/gentoo/dev             &&
mount	--rbind		/sys	/mnt/dev/gentoo/sys             &&
mount	--rbind		/proc	/mnt/dev/gentoo/proc            &&
mount	--rbind		/run	/mnt/dev/gentoo/run             &&
mount	/dev/sda4		/mnt/dev/gentoo/mnt/mss/stuff

# execute stuff
urxvt -e chroot /mnt/dev/gentoo su -c "zsh" mss

# umount garbage
umount	-l	/mnt/dev/gentoo/dev		&&
umount	-l	/mnt/dev/gentoo/sys		&&
umount	-l	/mnt/dev/gentoo/proc		&&
umount	-l	/mnt/dev/gentoo/run		&&
umount	-l	/mnt/dev/gentoo/mnt/mss/stuff
