#!/bin/env bash
export SUDO_ASKPASS=/home/mss/.config/i3/dmenu/dsudo
sel=$(echo -e "mightyluna\npl\ntransmission\nkill-i3\n" | dmenu -p "meh:")

case "$sel" in
 kill-i3)	i3-msg exit & ;;
 mightyluna)	mightyluna ;;
 transmission)	transmission-gtk ;;
 pl)	pl;;
esac
