#!/mss/bin/sh
. /mss/initbits/bin/apathy-init-funcs

case "${1}" in
 start)
  ainitmes "mounting ${c_lcyan}rootfs in ${c_lcyan}rw${c_reset} mode."
   mount -n -o remount,ro / >/dev/null 2>&1
  evalret

  ainitmes "running ${c_lcyan}fsck${c_reset}."
   fsck -a -A -C -T >/dev/null 2>&1
  evalret
 ;;
 *)
  ainitusage "{start}"
  exit 1
 ;;
esac
