#!/mss/bin/sh
. /mss/initbits/bin/apathy-init-funcs

UNICODE="1"
KEYMAP="us"
FONT="ter-v12n -m 8859-1"

case "${1}" in
 start)
  ainitmes "setting up the ${c_lcyan}consolefont${c_reset}."
   setfont ${FONT}
  evalret

  ainitmes "setting the ${c_lcyan}keymap${c_reset}."
   loadkeys ${KEYMAP} >/dev/null 2>&1
  evalret
 ;;
 *)
  ainitusage "{start}"
  exit 1
 ;;
esac
