#!/mss/bin/sh
. /mss/initbits/bin/apathy-init-funcs

PIDFILE=/run/earlyoom.pid
DAEMON=/sbin/earlyoom
DAEMON_OPTS="-p -r 0"
USER=root

case "$1" in
 start)
  ainitmes "starting ${c_lcyan}earlyoom${c_reset}."
   earlyoom -p -r 0 >/dev/null 2>&1 &
  evalret
 ;;
 stop)
  ainitmes "stopping ${c_lcyan}earlyoom${c_reset}."
   kill -TERM "$(pidof earlyoom)" >/dev/null 2>&1
  evalret
 ;;
 restart)
  ${0} stop; sleep 1; ${0} start
 ;;
 *)
  ainitusage "{start|stop|restart}"
  exit 1
 ;;
esac
