#!/mss/bin/sh
. /mss/initbits/bin/apathy-init-funcs

case "$1" in
 start)

  ainitmes "mounting: ${c_lcyan}/run${c_reset}"
   if ! mountpoint /run >/dev/null
    then mount /run
   fi                                           &&
   mkdir -p /run/lock /run/shm                  &&
   chmod 1777 /run/shm /run/lock                &&

  ainitmes_nospace " ${c_lcyan}/proc${c_reset}"
   if ! mountpoint /proc >/dev/null
    then mount -o nosuid,noexec,nodev /proc
   fi                                           &&

  ainitmes_nospace " ${c_lcyan}/sys${c_reset}"
   if ! mountpoint /sys >/dev/null
    then mount -o nosuid,noexec,nodev /sys
   fi                                           &&

  ainitmes_nospace " ${c_lcyan}/dev${c_reset}."
   if ! mountpoint /dev >/dev/null
    then mount -o mode=0755,nosuid /dev
   fi
  evalret

  ln -sfn /run/shm /dev/shm  
 ;;
 *)
  ainitusage "{start}"
  exit 1
 ;;
esac
