#!/mss/bin/sh
. /mss/initbits/bin/apathy-init-funcs

case "$1" in
 start)
  for blockdevice in /sys/block/sd*; do
   ainitmes "setting ${c_lcyan}bfq${c_reset} as the scheduler for ${c_lcyan}${blockdevice}${c_reset}."
    echo bfq > ${blockdevice}/queue/scheduler
   evalret
   sleep 1
  done
 ;;
 *)
  ainitusage "{start|stop}"
  exit 1
 ;;
esac
