#!/mss/bin/sh
. /mss/initbits/bin/apathy-init-funcs

case "$1" in
 start)
  ainitmes "setting ${c_lcyan}standard streams${c_reset}."
   cd /dev                        &&
   ln -sf /proc/self/fd/0  stdin  &&
   ln -sf /proc/self/fd/1  stdout &&
   ln -sf /proc/self/fd/2  stderr &&
   cd - 1>/dev/null
  evalret
 ;;
 *)
  ainitusage "{start}"
  exit 1
 ;;
esac
