#!/mss/bin/sh
. /mss/initbits/bin/apathy-init-funcs

case "$1" in
 start)
  ainitmes "activating ${c_lcyan}swap${c_reset}." 
   swapon -a >/dev/null 2>&1
  evalret
 ;;
 stop)
  ainitmes "deactivating ${c_lcyan}swap${c_reset}."
   swapoff -a >/dev/null 2>&1
  evalret
 ;;
 restart)
  ${0} stop; sleep 1; ${0} start
 ;;
 *)
  ainitusage "{start|stop|restart}"
  exit 1
 ;;
esac
