#!/mss/bin/sh
. /mss/initbits/bin/apathy-init-funcs

case "$1" in
 start)
  ainitmes "starting ${c_lcyan}udev${c_reset}."
   /sbin/udevd --daemon                                    && 
   /sbin/udevadm trigger --action=add    --type=subsystems &&
   /sbin/udevadm trigger --action=add    --type=devices    &&
   /sbin/udevadm trigger --action=change --type=devices
  evalret

  ainitmes "telling ${c_lcyan}udev${c_reset} to ${c_lcyan}settle${c_reset} if it did not already."
   [ -z "$OMIT_UDEV_SETTLE" ] && /sbin/udevadm settle
  evalret
 ;;
 *)
  ainitusage "{start}"
  exit 1
 ;;
esac
